/**
 * @generated
 * @file AdfinForPageDropdown (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { DropdownItem } from "./DropdownItem";
import { PageDropdown } from "./PageDropdown";

/**
 * AdfinForPageDropdown
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function AdfinForPageDropdown({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block tag={"div"}>
        <PageDropdown
          dropdownItem={
            <>
              <DropdownItem
                link={{
                  href: "/for/small-businesses",
                  preload: "prefetch",
                }}
                text={"Small Businesses"}
              />
              <DropdownItem
                link={{
                  href: "/for/growing-businesses",
                  preload: "prefetch",
                }}
                text={"Growing Businesses"}
              />
              <DropdownItem
                link={{
                  href: "/for/accountants-and-bookkeepers",
                  preload: "prefetch",
                }}
                text={"Accountant & Bookkeepers"}
              />
              <DropdownItem
                link={{
                  href: "/for/managed-service-providers",
                  preload: "prefetch",
                }}
                text={"Managed Service Providers"}
              />
            </>
          }
        />
      </Block>
    </div>
  );
}
