/**
 * @generated
 * @file AnchorLinks (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * AnchorLinks
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function AnchorLinks({ anchorLink }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"anchor-links_component"}
        data-component={"anchor-links"}
        tag={"div"}
      >
        <HtmlEmbed
          className={"u-embed-css"}
          content={
            "<style>\n  [data-component='anchor-border'].is-scrolling {\n    transition: none; /* instant while dragging the strip */\n  }\n</style>"
          }
        />
        {anchorLink}
        <Block
          className={"anchor-links_border"}
          data-anchor-links={"border"}
          tag={"div"}
        />
      </Block>
    </div>
  );
}
