/**
 * @generated
 * @file AnchorLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * AnchorLink
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function AnchorLink({
  active = false,

  link = {
    href: "#",
  },

  text = "Text",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"anchor-link_link"}
        data-anchor-links={"link"}
        options={link}
        {...{
          [active ? "class" : ""]: active ? "is-active" : "",
        }}
      >
        <Block tag={"div"}>{text}</Block>
      </Link>
    </div>
  );
}
