/**
 * @generated
 * @file BreadcrumbLayout (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { SpaceSwitcher } from "../variantSwitcher/SpaceSwitcher";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * BreadcrumbLayout
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function BreadcrumbLayout({
  breadcrumb,
  maxWidth = 40,
  spaceSwitcherMarginBottom = "None",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"breadcrumb_component"}
        data-number={formatNumber(-1)(maxWidth)}
        tag={"div"}
        {...{
          [spaceSwitcherMarginBottom !== "Square" ? "class" : ""]:
            spaceSwitcherMarginBottom === "Small"
              ? "u-margin-bottom-5"
              : spaceSwitcherMarginBottom === "Medium"
              ? "u-margin-bottom-8"
              : spaceSwitcherMarginBottom === "Large"
              ? "u-margin-bottom-main"
              : "",
        }}
      >
        {breadcrumb}
        <SpaceSwitcher variant={spaceSwitcherMarginBottom} />
      </Block>
    </div>
  );
}
