/**
 * @generated
 * @file BreadcrumbItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { Clickable } from "../utility/Clickable";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { linkIsSet } from "../webflow_modules/Basic/helpers/linkIsSet";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * BreadcrumbItem
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function BreadcrumbItem({
  link = {
    href: "/",
    preload: "prefetch",
  },

  text = "",
  variant = "Base",
  visibility = true,
}) {
  const _styleVariantMap = {
    Base: "",
    Current: "w-variant-5cb0a9ef-b200-a62d-f506-14099e8781dd",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          className={`breadcrumb_item ${_activeStyleVariant}`}
          data-trigger={"hover focus"}
          tag={"div"}
        >
          <Clickable
            link={
              applyPredicate(link)(linkIsSet)
                ? link
                : {
                    mode: "page",
                    pageId: "6a69cb8ca361f85b63b37e8b",
                  }
            }
            screenReaderText={text}
            visibility={variant === "Square" ? true : false}
          />
          <Block
            className={`breadcrumb_text u-text-style-eyebrow ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`u-line-clamp-1 ${_activeStyleVariant}`}
              tag={"div"}
            >
              {!!toText(text)
                ? text
                : variant === "Current"
                ? "Home"
                : ["Home"]}
            </Block>
          </Block>
          <PhosphorIcon
            classProp={"ph-arrow-square-right"}
            visibility={variant === "Square" ? true : false}
          />
        </Block>
      ) : null}
    </div>
  );
}
