/**
 * @generated
 * @file DropdownItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * DropdownItem
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function DropdownItem({
  link = {
    href: "#",
    preload: "prefetch",
  },

  text = "Text",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"dropdown_list_item"} tag={"li"}>
        <Link
          block={"inline"}
          button={false}
          className={"dropdown_list_link"}
          data-trigger={"hover-other"}
          options={link}
        >
          <Block
            className={"dropdown_list_text u-text-style-xsmall"}
            tag={"div"}
          >
            {text}
          </Block>
        </Link>
      </DOM>
    </div>
  );
}
