/**
 * @generated
 * @file PageDropdown (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { Dropdown } from "../interactive/Dropdown";
import { TypographyPlain } from "../typography/TypographyPlain";

/**
 * PageDropdown
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function PageDropdown({
  dropdownCloseOnHoverOut = true,
  dropdownItem,
  dropdownOpenOnHoverIn = true,
  dropdownPreviewContent = false,
  title = "Adfin for",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={"page-dropdown_wrap"} tag={"div"}>
          <HtmlEmbed
            className={"u-embed-css"}
            content={
              "<style>\n  .dropdown_list_item:has(.dropdown_list_link.w--current) {\n    display: none;\n  }\n</style>"
            }
          />
          <Block className={"page-dropdown_pre"} tag={"div"}>
            <TypographyPlain
              marginBottom={0}
              text={title}
              variant={"Text XSmall"}
            />
          </Block>
          <Dropdown
            content={
              <DOM
                className={"dropdown_list_wrap"}
                data-trigger={"group"}
                tag={"ul"}
              >
                {dropdownItem}
              </DOM>
            }
            previewContent={dropdownPreviewContent}
            settingsCloseOnHoverOut={dropdownCloseOnHoverOut}
            settingsOpenOnHoverIn={dropdownOpenOnHoverIn}
            settingsVisibility={true}
            text={"Home"}
          />
        </Block>
      ) : null}
    </div>
  );
}
