/**
 * @generated
 * @file Icon (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * Icon
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Icon({
  colour = true,
  settingsAriaHidden = false,
  settingsAttributes = {},
  settingsVisibility = true,
  svgIcon = '<svg width="66" height="70" viewBox="0 0 66 70" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M17 2L50 34.9999L17 68" stroke="white" stroke-width="2"/>\n</svg>',
  variant = "Full",
}) {
  const _styleVariantMap = {
    Full: "",
    Small: "w-variant-8f27d1c8-d95a-e3b2-66d1-3a165d05aede",
    Medium: "w-variant-6c22932d-bc07-1741-25e0-ad3c03857826",
    Large: "w-variant-004e1ee3-faf9-8df4-6b9d-7a8d0aa017b1",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <HtmlEmbed
          className={`u-icon ${_activeStyleVariant}`}
          data-color-current={null}
          {...{
            [settingsAriaHidden ? "aria-hidden" : ""]: settingsAriaHidden
              ? "true"
              : "",
          }}
          {...settingsAttributes}
        />
      ) : null}
    </div>
  );
}
