/**
 * @generated
 * @file IconArrow (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { Icon } from "./Icon";

/**
 * IconArrow
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function IconArrow({ direction = "Right", size = "Full" }) {
  const _styleVariantMap = {
    Right: "",
    Left: "w-variant-dc469724-71a3-14e1-b5d5-1294323411ce",
    Top: "w-variant-b18a0fcd-abb0-329e-47f4-79155dd8284a",
    Bottom: "w-variant-caa8b8e9-e8ec-6eb3-4526-30f19f7326f5",
  };

  const _activeStyleVariant = _styleVariantMap[direction];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={`u-svg ${_activeStyleVariant}`} tag={"div"}>
        <Icon variant={size} />
      </DOM>
    </div>
  );
}
