/**
 * @generated
 * @file IconArrowFull (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { PhosphorIcon } from "../typography/PhosphorIcon";

/**
 * IconArrowFull
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function IconArrowFull({ variant = "Right" }) {
  const _styleVariantMap = {
    Right: "",
    Left: "w-variant-1c3f028b-116e-d4eb-db7f-8484491bbf2e",
    Top: "w-variant-a0a4b133-f837-5340-6c98-04b1518f150d",
    Bottom: "w-variant-5939aeba-b378-ecdc-f1bc-b6970df2be03",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={`u-svg ${_activeStyleVariant}`} tag={"div"}>
        <PhosphorIcon classProp={"ph-arrow-right"} />
      </DOM>
    </div>
  );
}
