/**
 * @generated
 * @file Logo (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * Logo
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Logo({ settingsStyle = "", settingsVisibility = true }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={"u-max-width-full"}
          // @ts-ignore - User-defined custom attribute(s)
          style={settingsStyle}
          tag={"div"}
        >
          <HtmlEmbed
            className={"u-icon"}
            content={
              '<svg width="100%" viewBox="0 0 94 32" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M16.3475 1.73254H4.08748V5.80939H0V30.2669H8.17376V22.1144H12.2612V30.2669H20.435V5.80939H16.3475V1.73254ZM12.2612 18.0375H8.17376V5.80939H12.2612V18.0387V18.0375Z" fill="currentColor"/>\n<path d="M35.756 9.88504H23.4863V30.2669H43.9297V1.73254H35.756V9.88504ZM35.756 26.19H31.6601V13.9607H35.756V26.19Z" fill="currentColor"/>\n<path d="M48.025 1.73254V9.88504H45.998V13.9619H48.025V30.2669H56.1987V13.9619H60.2862V9.88504H56.1987V5.80939H60.2862V1.73254H48.025Z" fill="currentColor"/>\n<path d="M70.538 1.73254H62.3643V5.80939H70.538V1.73254Z" fill="currentColor"/>\n<path d="M70.538 9.88733H62.3643V30.2692H70.538V9.88733Z" fill="currentColor"/>\n<path d="M89.9122 13.9642V9.88733H73.5635V30.2692H81.7372V13.9642H85.8247V30.2692H93.9985V13.9642H89.9122Z" fill="currentColor"/>\n</svg>'
            }
          />
        </DOM>
      ) : null}
    </div>
  );
}
