/**
 * @generated
 * @file AccordionItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import RichText from "../webflow_modules/Basic/components/RichText";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * AccordionItem
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function AccordionItem({
  heading = "This is some text inside of a div block.",
  paragraph = "",
  settingsClasses = "",
  settingsHeadingTag = "h3",
  settingsVisibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !!toText(heading) ? (
        <DOM
          className={"accordion_item"}
          data-state={" "}
          role={"listitem"}
          tag={"div"}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <Block className={"accordion_component"} tag={"div"}>
            <DOM
              className={"accordion_toggle_heading"}
              tag={settingsHeadingTag}
            >
              <DOM
                aria-expanded={"false"}
                className={"accordion_toggle_button"}
                tag={"button"}
              >
                <DOM
                  className={"accordion_toggle_text u-text-style-main"}
                  tag={"span"}
                >
                  {heading}
                </DOM>
                <DOM className={"accordion_toggle_icon"} tag={"span"}>
                  <PhosphorIcon classProp={"ph-plus"} variant={"Large"} />
                </DOM>
              </DOM>
            </DOM>
            <Block className={"accordion_content_wrap"} tag={"div"}>
              <Block className={"accordion_content_padding"} tag={"div"}>
                <RichText
                  className={"accordion_content_text u-rich-text"}
                  tag={"div"}
                >
                  {paragraph}
                </RichText>
              </Block>
            </Block>
          </Block>
        </DOM>
      ) : null}
    </div>
  );
}
