/**
 * @generated
 * @file FramedTabLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FramedTabLink
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FramedTabLink({
  settingsClasses = "",
  settingsItemId = "",
  settingsVisibility = false,
  text = "Tab Link",
  variant = "Link",
}) {
  const _styleVariantMap = {
    Link: "",
    Button: "w-variant-8ffc88d1-7ba2-15f6-9b67-306f6d86c1bd",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!!toText(text) && settingsVisibility ? (
        <DOM
          className={`framed-tab_button_item ${_activeStyleVariant}`}
          tag={"button"}
          {...{
            [settingsItemId !== "" ? "data-tab-item-id" : ""]: settingsItemId,
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <DOM
            className={`framed-tab_button_text u-text-style-small ${_activeStyleVariant}`}
            tag={"span"}
          >
            {text}
          </DOM>
        </DOM>
      ) : null}
    </div>
  );
}
