/**
 * @generated
 * @file Marquee (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";

/**
 * Marquee
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Marquee({ classes = "", content, duration = 20, id = "" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!slotIsEmpty(content) ? (
        <Block
          className={`marquee_component ${classes}`}
          data-marquee-id={id}
          tag={"div"}
        >
          <HtmlEmbed className={"u-embed-css"} />
          {content}
        </Block>
      ) : null}
    </div>
  );
}
