/**
 * @generated
 * @file ProgressTabs (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { CardsList } from "../card/CardsList";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * ProgressTabs
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ProgressTabs({
  card,
  duration = 5,
  loop = false,
  minWidth = 18,
  theme = "Inherit",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"progress-tabs_component"}
        data-component={"progress-tab"}
        data-duration={formatNumber(-1)(duration)}
        data-loop={null}
        tag={"div"}
      >
        <CardsList card={card} settingsMinWidth={minWidth} theme={theme} />
      </Block>
    </div>
  );
}
