/**
 * @generated
 * @file SliderControls (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { ButtonArrow } from "../button/ButtonArrow";

/**
 * SliderControls
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function SliderControls({ variant = "Base", visibility = true }) {
  const _styleVariantMap = {
    Base: "",
    Progress: "w-variant-919e6135-b534-bce4-1d16-3931ae93686b",
    Hidden: "w-variant-4d6fca91-cf3e-0db5-5be1-ef7fa59bf98f",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          className={`slider_controls ${_activeStyleVariant}`}
          data-variant={
            variant === "Square"
              ? "Base"
              : variant === "Progress"
              ? "Progress"
              : ""
          }
          tag={"div"}
        >
          <Block
            className={`slider_button_layout ${_activeStyleVariant}`}
            tag={"div"}
          >
            <ButtonArrow
              arrowDirection={"Left"}
              link={{
                href: "#",
              }}
              settingsClasses={""}
              settingsClickableAttributes={{
                "data-slider": "previous",
              }}
              settingsVisibility={variant === "Square" ? true : false}
              text={"Previous"}
              variant={"Secondary / Medium"}
            />
            <Block
              className={`slider_bullet_list ${_activeStyleVariant}`}
              tag={"div"}
            >
              <DOM
                className={`slider_bullet_item is-active ${_activeStyleVariant}`}
                data-slider={"bullet"}
                style={{
                  "--progress": " 1",
                }}
                tag={"div"}
              >
                <Block
                  className={`slider_bullet_progress ${_activeStyleVariant}`}
                  tag={"div"}
                />
              </DOM>
              <DOM
                className={`slider_bullet_item ${_activeStyleVariant}`}
                data-slider={"bullet"}
                style={{
                  "--progress": " 1",
                }}
                tag={"div"}
              >
                <Block
                  className={`slider_bullet_progress ${_activeStyleVariant}`}
                  tag={"div"}
                />
              </DOM>
            </Block>
            <ButtonArrow
              arrowDirection={"Left"}
              link={{
                href: "#",
              }}
              settingsClasses={""}
              settingsClickableAttributes={{
                "data-slider": "previous",
              }}
              settingsVisibility={variant === "Progress" ? true : false}
              text={"Previous"}
              variant={"Secondary / Medium"}
            />
            <ButtonArrow
              arrowDirection={"Right"}
              link={{
                href: "#",
              }}
              settingsClasses={""}
              settingsClickableAttributes={{
                "data-slider": "next",
              }}
              settingsVisibility={true}
              text={"Next"}
              variant={"Secondary / Medium"}
            />
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
