/**
 * @generated
 * @file SliderAsset (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { VisualImage } from "../visual/VisualImage";

/**
 * SliderAsset
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function SliderAsset({
  aspectRatio = "Square 1 / 1",
  image = "",
  settingsVisibility = false,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM className={"card_primary_wrap"} role={"listitem"} tag={"div"}>
          <Block className={"card_primary_group"} tag={"div"}>
            <VisualImage image={image} variant={aspectRatio} />
          </Block>
        </DOM>
      ) : null}
    </div>
  );
}
