/**
 * @generated
 * @file TabLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * TabLink
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TabLink({
  phosphorIconClass = "ph-x",
  phosphorIconVisibility = false,
  settingsClasses = "",
  settingsItemId = "",
  settingsVisibility = false,
  text = "Tab Link",
  variant = "Link",
}) {
  const _styleVariantMap = {
    Link: "",
    "Link Grey": "w-variant-b3b35b62-3b20-ce7b-d483-070455acdaaa",
    Button: "w-variant-d4250984-191c-20e7-3436-65e4fef7325b",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!!toText(text) && settingsVisibility ? (
        <DOM
          className={`tab_button_item ${_activeStyleVariant}`}
          tag={"button"}
          {...{
            [settingsItemId !== "" ? "data-tab-item-id" : ""]: settingsItemId,
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <PhosphorIcon
            classProp={phosphorIconClass}
            variant={"Large"}
            visibility={phosphorIconVisibility}
          />
          <DOM
            className={`tab_button_text u-text-style-small ${_activeStyleVariant}`}
            tag={"span"}
          >
            {text}
          </DOM>
        </DOM>
      ) : null}
    </div>
  );
}
