/**
 * @generated
 * @file CheckListItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { PhosphorIcon } from "../typography/PhosphorIcon";

/**
 * CheckListItem
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CheckListItem({
  main = "Laborum quis laborum fugiat nulla tempor",
  sub = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"check-list_item"}
        // @ts-ignore - User-defined custom attribute(s)
        role={"listitem"}
        tag={"div"}
      >
        <PhosphorIcon classProp={"ph-check-circle u-color-accent"} />
        <Block className={"check-list_text"} tag={"div"}>
          <Block className={"check-list_text_main"} tag={"div"}>
            <Block className={"u-text-style-small"} tag={"div"}>
              {main}
            </Block>
          </Block>
          <Block className={"u-text-style-small u-faded"} tag={"div"}>
            {sub}
          </Block>
        </Block>
      </Block>
    </div>
  );
}
