/**
 * @generated
 * @file CheckUi (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * CheckUi
 *
 * Used inside Form Checkbox and Form Radio Components
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CheckUi({
  checked = false,
  label = "I agree to the terms",
  name = "",
  required = false,
  settingsInputAttributes = {},
  settingsLabelAttributes = {},
  settingsVariant = "Checkbox",
  type = false,
  value = "Value",
}) {
  const _styleVariantMap = {
    Checkbox: "",
    Toggle: "w-variant-05ff758a-80c8-4344-649b-149f87b62cc9",
    Button: "w-variant-e3978449-fef8-38a6-7f29-4e26ca4f8f53",
    Radio: "w-variant-c18f59b8-0331-9f8c-c106-08818710cc20",
  };

  const _activeStyleVariant = _styleVariantMap[settingsVariant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        className={`form_ui_label ${_activeStyleVariant}`}
        data-state={"checked"}
        tag={"label"}
      >
        <DOM className={`form_ui_input ${_activeStyleVariant}`} tag={"input"} />
        <DOM
          className={`form_ui_visual_wrap ${_activeStyleVariant}`}
          tag={"span"}
        >
          <DOM
            className={`form_ui_visual_inner ${_activeStyleVariant}`}
            tag={"span"}
          >
            <DOM
              aria-hidden={"true"}
              className={`form_ui_visual_icon ${_activeStyleVariant}`}
              fill={"none"}
              tag={"svg"}
              viewBox={"0 0 11 8"}
            >
              <DOM
                d={"M1 4L4 7L10 1"}
                stroke={"currentColor"}
                strokeWidth={"0.125rem"}
                tag={"path"}
                vectorEffect={"non-scaling-stroke"}
              />
            </DOM>
          </DOM>
        </DOM>
        <DOM className={`form_ui_text ${_activeStyleVariant}`} tag={"span"}>
          {label}
        </DOM>
      </DOM>
    </div>
  );
}
