/**
 * @generated
 * @file ComparisonTable (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { ComparisonCell } from "./ComparisonCell";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * ComparisonTable
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ComparisonTable({
  comparisonGroup,
  footnoteText = "",
  footnoteVisibility = true,
  id = "",
  openByDefault = 1,
  previewContent = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"comparison-list_component u-text-style-small"}
        data-comparison-table-id={id}
        data-component={"comparison-table"}
        data-open-by-default={formatNumber(-1)(openByDefault)}
        data-preview={null}
        id={id}
        tag={"div"}
      >
        <HtmlEmbed
          className={"u-embed-css"}
          content={
            "<style>\n  .wf-design-mode [data-component=\"comparison-table\"][data-preview='True'] [data-comparison-table=\"body\"] {\n    display: flex;\n  }\n  \n  [data-component='comparison-table'][data-open-by-default='-1'] [data-comparison-table=\"body\"] {\n    display: flex;\n  }\n  \n  [data-component='comparison-table'][data-open-by-default='1'] [data-comparison-table=\"group\"]:first-child [data-comparison-table=\"body\"] {\n    display: flex;\n  }\n</style>"
          }
        />
        {comparisonGroup}
        <ComparisonCell
          bodyColour={false}
          bodyText={footnoteText}
          bodyVariant={"Text XSmall"}
          visibility={footnoteVisibility}
        />
        <HtmlEmbed className={"u-embed-js"} />
      </Block>
    </div>
  );
}
