/**
 * @generated
 * @file ComparisonGroup (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Heading from "../webflow_modules/Basic/components/Heading";
import { PhosphorIcon } from "../typography/PhosphorIcon";

/**
 * ComparisonGroup
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ComparisonGroup({ comparisonRow, title = "Title" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"comparison-list_group"}
        data-comparison-table={"group"}
        data-state={""}
        tag={"div"}
      >
        <DOM
          aria-expanded={"false"}
          className={"comparison-list_header"}
          data-comparison-table={"header"}
          tag={"button"}
        >
          <Block className={"comparison-list_cell is-header"} tag={"div"}>
            <Heading
              className={"u-text-style-small u-weight-semibold"}
              tag={"h4"}
            >
              {title}
            </Heading>
          </Block>
          <Block className={"comparison-list_toggle"} tag={"div"}>
            <PhosphorIcon classProp={"ph-plus"} variant={"Large"} />
          </Block>
        </DOM>
        <Block
          className={"comparison-list_body"}
          data-comparison-table={"body"}
          tag={"div"}
        >
          {comparisonRow}
        </Block>
      </Block>
    </div>
  );
}
