/**
 * @generated
 * @file ComparisonCell (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { TypographyParagraph } from "../typography/TypographyParagraph";

/**
 * ComparisonCell
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ComparisonCell({
  bodyColour = true,
  bodyText = "",
  bodyVariant = "Inherit",
  bodyVisibility = true,
  iconClass = "ph-check-square",
  iconVisibility = false,
  titleTag = "h5",
  titleText = "Title",
  titleVisibility = false,
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={"comparison-list_cell"} tag={"div"}>
          <PhosphorIcon
            classProp={iconClass}
            variant={"Large"}
            visibility={iconVisibility}
          />
          <Block className={"comparison-list_cell_content"} tag={"div"}>
            {titleVisibility ? (
              <Heading
                className={"u-text-style-small u-weight-semibold"}
                tag={titleTag}
              >
                {titleText}
              </Heading>
            ) : null}
            <TypographyParagraph
              colour={bodyColour}
              marginBottom={0}
              maxWidth={-1}
              settingsVisibility={bodyVisibility}
              text={bodyText}
              variant={bodyVariant}
            />
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
