/**
 * @generated
 * @file FooterLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * FooterLink
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FooterLink({
  attributes = {},

  link = {
    href: "#",
    preload: "prefetch",
  },

  settingsVisibility = true,
  text = "Link Text Here",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={"footer_group_item"}
          data-trigger={"hover-other focus-other"}
          role={"listitem"}
          tag={"div"}
        >
          <Link
            block={"inline"}
            button={false}
            className={"footer_link_wrap"}
            options={link}
            {...attributes}
          >
            <Block
              className={"footer_link_text u-text-style-small"}
              tag={"div"}
            >
              {text}
            </Block>
          </Link>
        </DOM>
      ) : null}
    </div>
  );
}
