/**
 * @generated
 * @file FooterGroup (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Heading from "../webflow_modules/Basic/components/Heading";
import Section from "../webflow_modules/Layout/components/Section";

/**
 * FooterGroup
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FooterGroup({
  footerLink,
  settingsVisibility = true,
  title = "Heading Text",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <Section
          className={"footer_group_wrap"}
          data-trigger={"group"}
          tag={"section"}
        >
          <Heading
            className={
              "footer_group_title u-text-style-xsmall u-margin-bottom-text u-faded"
            }
            tag={"h3"}
          >
            {title}
          </Heading>
          {footerLink}
        </Section>
      ) : null}
    </div>
  );
}
