/**
 * @generated
 * @file Menu (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import DropdownList from "../webflow_modules/Dropdown/components/DropdownList";
import DropdownToggle from "../webflow_modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "../webflow_modules/Dropdown/components/DropdownWrapper";
import Link from "../webflow_modules/Basic/components/Link";
import List from "../webflow_modules/Basic/components/List";
import ListItem from "../webflow_modules/Basic/components/ListItem";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";
import SearchButton from "../webflow_modules/Search/components/SearchButton";
import SearchForm from "../webflow_modules/Search/components/SearchForm";
import SearchInput from "../webflow_modules/Search/components/SearchInput";
import { ButtonMain } from "../button/ButtonMain";
import { Icon } from "../svg/Icon";
import { IconArrow } from "../svg/IconArrow";
import { NavDropdownList } from "../NavDropdownList";
import { NavDropdownListItem } from "../NavDropdownListItem";
import { PhosphorIcon } from "../typography/PhosphorIcon";

/**
 * Menu
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Menu({ variant = "Mobile" }) {
  const _styleVariantMap = {
    Mobile: "",
    Desktop: "w-variant-23049969-09ac-2789-520b-3c6ae895bbc6",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        aria-label={"Main"}
        className={`nav_links_component ${_activeStyleVariant}`}
        tag={"nav"}
      >
        <Block
          className={`nav_links_list ${_activeStyleVariant}`}
          data-trigger={"group"}
          // @ts-ignore - User-defined custom attribute(s)
          role={"list"}
          tag={"div"}
        >
          <Block
            className={`nav_links_item ${_activeStyleVariant}`}
            // @ts-ignore - User-defined custom attribute(s)
            role={"listitem"}
            tag={"div"}
          >
            <DropdownWrapper
              className={`nav_dropdown_component ${_activeStyleVariant}`}
              delay={350}
              hover={true}
              tag={"div"}
            >
              <DropdownToggle
                className={`nav_links_link ${_activeStyleVariant}`}
                data-state={"expanded open"}
                data-trigger={"hover-other"}
                tag={"div"}
              >
                <Block
                  className={`nav_links_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Product"}
                </Block>
                <Block
                  className={`nav_links_icon ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <PhosphorIcon classProp={"ph-caret-down"} variant={"Small"} />
                </Block>
              </DropdownToggle>
              <DropdownList
                className={`nav_dropdown_mega_wrap ${_activeStyleVariant}`}
                tag={"nav"}
              >
                <Block
                  className={`nav_dropdown_mega_content ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav_dropdown_mega_scroll ${_activeStyleVariant}`}
                    data-lenis-prevent={""}
                    tag={"div"}
                  >
                    <Block
                      className={`nav_dropdown_mega_contain ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`nav_dropdown_mega_layout ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`nav_dropdown_mega_group is-first ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Platform"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <>
                                <NavDropdownListItem
                                  link={{
                                    href: "/accept-payments",
                                    preload: "prefetch",
                                  }}
                                  sub={"All payments. One platform."}
                                  title={"Payments"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/credit-control",
                                    preload: "prefetch",
                                  }}
                                  sub={"Credit control, on your terms."}
                                  title={"Credit Control"}
                                />
                              </>
                            }
                          />
                        </Block>
                        <Block
                          className={`nav_dropdown_mega_group ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Partners"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <>
                                <NavDropdownListItem
                                  link={{
                                    href: "/partners/xero",
                                    preload: "prefetch",
                                  }}
                                  title={"Xero"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/partners/quickbooks",
                                    preload: "prefetch",
                                  }}
                                  title={"Quickbooks"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/partners/engager",
                                    preload: "prefetch",
                                  }}
                                  title={"Engager.app"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/partners/socket",
                                    preload: "prefetch",
                                  }}
                                  title={"Socket"}
                                />
                              </>
                            }
                          />
                        </Block>
                        <Block
                          className={`nav_dropdown_mega_group is-last ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Quicklinks"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <>
                                <NavDropdownListItem
                                  link={{
                                    href: "/resources/changelog",
                                    preload: "prefetch",
                                  }}
                                  title={"Changelog"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/legal",
                                    preload: "prefetch",
                                  }}
                                  title={"Legal"}
                                />
                              </>
                            }
                          />
                        </Block>
                      </Block>
                    </Block>
                  </Block>
                </Block>
              </DropdownList>
            </DropdownWrapper>
          </Block>
          <Block
            className={`nav_links_item ${_activeStyleVariant}`}
            // @ts-ignore - User-defined custom attribute(s)
            role={"listitem"}
            tag={"div"}
          >
            <DropdownWrapper
              className={`nav_dropdown_component ${_activeStyleVariant}`}
              delay={350}
              hover={true}
              tag={"div"}
            >
              <DropdownToggle
                className={`nav_links_link ${_activeStyleVariant}`}
                data-state={"expanded open"}
                data-trigger={"hover-other"}
                tag={"div"}
              >
                <Block
                  className={`nav_links_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Customers"}
                </Block>
                <Block
                  className={`nav_links_icon ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <PhosphorIcon classProp={"ph-caret-down"} variant={"Small"} />
                </Block>
              </DropdownToggle>
              <DropdownList
                className={`nav_dropdown_mega_wrap ${_activeStyleVariant}`}
                tag={"nav"}
              >
                <Block
                  className={`nav_dropdown_mega_content ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav_dropdown_mega_scroll ${_activeStyleVariant}`}
                    data-lenis-prevent={""}
                    tag={"div"}
                  >
                    <Block
                      className={`nav_dropdown_mega_contain ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`nav_dropdown_mega_layout ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`nav_dropdown_mega_group is-first ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Customers"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <>
                                <NavDropdownListItem
                                  link={{
                                    href: "/for/small-businesses",
                                    preload: "prefetch",
                                  }}
                                  sub={
                                    "Set up your payments stack the right way"
                                  }
                                  title={"Small Businesses"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/for/growing-businesses",
                                    preload: "prefetch",
                                  }}
                                  sub={"Maintain healthy cashflow as you scale"}
                                  title={"Growing Businesses"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/for/accountants-and-bookkeepers",
                                    preload: "prefetch",
                                  }}
                                  sub={
                                    "Get paid faster, and help your clients get paid"
                                  }
                                  title={"Accountants & Bookkeepers"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/for/managed-service-providers",
                                    preload: "prefetch",
                                  }}
                                  sub={"Recurring billing built for MSPs"}
                                  title={"MSPs"}
                                />
                              </>
                            }
                          />
                        </Block>
                        <Block
                          className={`nav_dropdown_mega_group ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Customer stories"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <NotSupported _atom={"Collection List"} />
                            }
                          />
                          <ButtonMain
                            text={"Explore all Customer Stories"}
                            variant={"Link"}
                          />
                        </Block>
                        <Block
                          className={`nav_dropdown_mega_group is-last ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Quicklinks"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <NavDropdownListItem
                                link={{
                                  href: "/resources/changelog",
                                  preload: "prefetch",
                                }}
                                title={"Changelog"}
                              />
                            }
                          />
                        </Block>
                      </Block>
                    </Block>
                  </Block>
                </Block>
              </DropdownList>
            </DropdownWrapper>
          </Block>
          <Block
            className={`nav_links_item ${_activeStyleVariant}`}
            // @ts-ignore - User-defined custom attribute(s)
            role={"listitem"}
            tag={"div"}
          >
            <DropdownWrapper
              className={`nav_dropdown_component ${_activeStyleVariant}`}
              delay={350}
              hover={true}
              tag={"div"}
            >
              <DropdownToggle
                className={`nav_links_link ${_activeStyleVariant}`}
                data-state={"expanded open"}
                data-trigger={"hover-other"}
                tag={"div"}
              >
                <Block
                  className={`nav_links_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Resources"}
                </Block>
                <Block
                  className={`nav_links_icon ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <PhosphorIcon classProp={"ph-caret-down"} variant={"Small"} />
                </Block>
              </DropdownToggle>
              <DropdownList
                className={`nav_dropdown_mega_wrap ${_activeStyleVariant}`}
                tag={"nav"}
              >
                <Block
                  className={`nav_dropdown_mega_content ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`nav_dropdown_mega_scroll ${_activeStyleVariant}`}
                    data-lenis-prevent={""}
                    tag={"div"}
                  >
                    <Block
                      className={`nav_dropdown_mega_contain ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`nav_dropdown_mega_layout ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`nav_dropdown_mega_group is-first ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Read"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <>
                                <NavDropdownListItem
                                  link={{
                                    href: "/customer-stories",
                                    preload: "prefetch",
                                  }}
                                  sub={"How businesses use Adfin"}
                                  title={"Customer Stories"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/resources/blog",
                                    preload: "prefetch",
                                  }}
                                  sub={"Industry news and updates"}
                                  title={"Blog"}
                                />
                              </>
                            }
                          />
                        </Block>
                        <Block
                          className={`nav_dropdown_mega_group ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Engage"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <>
                                <NavDropdownListItem
                                  link={{
                                    href: "/resources/events",
                                    preload: "prefetch",
                                  }}
                                  sub={"In-person and online"}
                                  title={"Events"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/abc-club",
                                    preload: "prefetch",
                                  }}
                                  sub={"Join our referral programme"}
                                  title={"The ABC Club"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "https://support.adfin.com/en/",
                                    target: "_blank",
                                  }}
                                  sub={"How-to guides and explainers"}
                                  title={"Help centre"}
                                />
                              </>
                            }
                          />
                        </Block>
                        <Block
                          className={`nav_dropdown_mega_group ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Company"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <>
                                <NavDropdownListItem
                                  link={{
                                    href: "/about",
                                    preload: "prefetch",
                                  }}
                                  sub={"Who we are"}
                                  title={"About"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/careers",
                                    preload: "prefetch",
                                  }}
                                  sub={"Open roles"}
                                  title={"Careers"}
                                />
                                <NavDropdownListItem
                                  link={{
                                    href: "/resources/changelog",
                                    preload: "prefetch",
                                  }}
                                  sub={"Product updates"}
                                  title={"Changelog"}
                                />
                              </>
                            }
                          />
                        </Block>
                        <Block
                          className={`nav_dropdown_mega_group is-last ${_activeStyleVariant}`}
                          tag={"div"}
                        >
                          <Block
                            className={`u-text-style-eyebrow ${_activeStyleVariant}`}
                            tag={"div"}
                          >
                            {"Legal"}
                          </Block>
                          <NavDropdownList
                            navDropdownList={
                              <NavDropdownListItem
                                link={{
                                  href: "/legal",
                                  preload: "prefetch",
                                }}
                                title={"Legal"}
                              />
                            }
                          />
                        </Block>
                      </Block>
                    </Block>
                  </Block>
                </Block>
              </DropdownList>
            </DropdownWrapper>
          </Block>
          <Block
            className={`nav_links_item ${_activeStyleVariant}`}
            // @ts-ignore - User-defined custom attribute(s)
            role={"listitem"}
            tag={"div"}
          >
            <Link
              block={"inline"}
              button={false}
              className={`nav_links_link ${_activeStyleVariant}`}
              options={{
                href: "/pricing",
                preload: "prerender",
              }}
            >
              <Block
                className={`nav_links_text ${_activeStyleVariant}`}
                tag={"div"}
              >
                {"Pricing"}
              </Block>
            </Link>
          </Block>
        </Block>
        <Block
          className={`nav_actions_wrap ${_activeStyleVariant}`}
          // @ts-ignore - User-defined custom attribute(s)
          role={"list"}
          tag={"div"}
        >
          <Block
            className={`nav_buttons_item ${_activeStyleVariant}`}
            // @ts-ignore - User-defined custom attribute(s)
            role={"listitem"}
            tag={"div"}
          >
            <ButtonMain
              icon2={"ph-user-circle-dashed"}
              iconVisibility={true}
              link={{
                href: "https://console.adfin.com/",
              }}
              text={"Sign in"}
              variant={"Secondary"}
            />
          </Block>
          <Block
            className={`nav_buttons_item ${_activeStyleVariant}`}
            // @ts-ignore - User-defined custom attribute(s)
            role={"listitem"}
            tag={"div"}
          >
            <ButtonMain
              link={{
                href: "/book-a-demo",
                preload: "prerender",
              }}
              text={"Book a demo"}
              variant={"Primary"}
            />
          </Block>
        </Block>
      </Block>
    </div>
  );
}
