/**
 * @generated
 * @file NavBanner (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Link from "../webflow_modules/Basic/components/Link";
import { PhosphorIcon } from "../typography/PhosphorIcon";

/**
 * NavBanner
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function NavBanner({
  link = {
    href: "#",
  },

  text = "Important Update Banner",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          aria-label={"Announcement"}
          className={"nav_banner_wrap"}
          // @ts-ignore - User-defined custom attribute(s)
          role={"region"}
          tag={"div"}
        >
          <Block className={"nav_banner_contain"} tag={"div"}>
            <Link
              block={"inline"}
              button={false}
              className={"nav_banner_link"}
              data-state={"external"}
              options={link}
            >
              <Block className={"nav_banner_text u-line-clamp-1"} tag={"div"}>
                {text}
              </Block>
              <DOM className={"nav_banner_icon"} tag={"div"}>
                <PhosphorIcon classProp={"ph-arrow-right"} variant={"Small"} />
              </DOM>
            </Link>
            <DOM
              className={"nav_banner_close_wrap"}
              role={"button"}
              tag={"button"}
            >
              <PhosphorIcon />
              <DOM className={"nav_screen-reader-text"} tag={"span"}>
                {"Close Announcement Banner"}
              </DOM>
            </DOM>
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
