/**
 * @generated
 * @file PopoverTarget (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * PopoverTarget
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function PopoverTarget({
  id = "popover-target-id",
  maxWidth = 40,
  text = "Nostrud ullamco sint esse minim elit tempor sint. Reprehenderit minim ipsum sit nostrud cupidatat esse.",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"u-popover-target"}
        data-number={formatNumber(-1)(maxWidth)}
        id={id}
        // @ts-ignore - User-defined custom attribute(s)
        popover={"hint"}
        tag={"div"}
      >
        {text}
      </Block>
    </div>
  );
}
