/**
 * @generated
 * @file PopoverTrigger (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * PopoverTrigger
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function PopoverTrigger({
  idFor = "popover-target-id",
  showPeriod = false,
  text = "popover trigger",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM tag={"span"}>
        <DOM aria-hidden={"true"} className={"u-inline-space"} tag={"span"} />
        <DOM className={"no-break"} tag={"span"}>
          <DOM
            className={"u-popover-trigger"}
            // @ts-ignore - User-defined custom attribute(s)
            interestfor={idFor}
            tag={"button"}
          >
            {text}
          </DOM>
          {showPeriod ? <DOM tag={"span"}>{"."}</DOM> : null}
        </DOM>
        <DOM
          aria-hidden={"true"}
          className={"u-inline-space"}
          tag={"span"}
          {...{
            [showPeriod ? "data-has-period" : ""]: null,
          }}
        />
      </DOM>
    </div>
  );
}
