/**
 * @generated
 * @file ResourceMeta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * ResourceMeta
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ResourceMeta({
  publishDate = "MMMM D, YYYY",
  readTime = "N",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={"resource_meta u-text-style-eyebrow"} tag={"div"}>
          <DOM className={"u-text-transform-uppercase"} tag={"div"}>
            <DOM tag={"span"}>{readTime}</DOM>
            <DOM tag={"span"}>{"min read"}</DOM>
          </DOM>
          <Block className={"u-dot"} tag={"div"} />
          <Block className={"u-text-transform-uppercase"} tag={"div"}>
            {publishDate}
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
