/**
 * @generated
 * @file TocLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * TocLink
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TocLink({
  link = {
    href: "#",
  },

  text = "Anchor link",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          className={"toc_item"}
          // @ts-ignore - User-defined custom attribute(s)
          role={"listitem"}
          tag={"div"}
        >
          <Link
            button={false}
            className={"toc_link"}
            data-trigger={"hover focus"}
            fs-toc-element={"link"}
            options={link}
            // @ts-ignore - User-defined custom attribute(s)
            role={"listitem"}
          >
            {text}
          </Link>
        </Block>
      ) : null}
    </div>
  );
}
