// Regenerate src/PricingCalculator/fonts.ts from the subset woff2 files.
// The Söhne font files are commercial (Klim) and are gitignored — they are NOT
// redistributed in this public repo. To (re)build locally:
//   1. Place subset woff2 files at src/PricingCalculator/fonts/sohne-buch.woff2 (400)
//      and sohne-kraeftig.woff2 (500). Subset from the licensed OTFs with:
//      python3 -m fontTools.subset Söhne-Buch.otf \
//        --unicodes="U+0020-007E,U+00A0-00FF,U+2013,U+2014,U+2018,U+2019,U+201C,U+201D,U+2022,U+2026" \
//        --flavor=woff2 --output-file=src/PricingCalculator/fonts/sohne-buch.woff2
//   2. Run: npm run embed-fonts
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const dir = resolve(dirname(fileURLToPath(import.meta.url)), '../src/PricingCalculator');
const face = (w, f) =>
  `@font-face{font-family:"Söhne";font-style:normal;font-weight:${w};font-display:swap;` +
  `src:url(data:font/woff2;base64,${readFileSync(`${dir}/fonts/${f}`).toString('base64')}) format("woff2");}`;

const out =
  `// Auto-generated by scripts/embed-fonts.mjs. Söhne (Buch 400, Kräftig 500), subset\n` +
  `// to Latin + common punctuation, woff2, embedded so they load inside the Shadow DOM.\n` +
  `export const fontFaceCss = \`\n${face(400, 'sohne-buch.woff2')}\n${face(500, 'sohne-kraeftig.woff2')}\n\`;\n`;

writeFileSync(`${dir}/fonts.ts`, out);
console.log('wrote src/PricingCalculator/fonts.ts');
