/**
 * @generated
 * @file ContactForm (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import FormErrorMessage from "../webflow_modules/Form/components/FormErrorMessage";
import FormForm from "../webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "../webflow_modules/Form/components/FormSuccessMessage";
import FormWrapper from "../webflow_modules/Form/components/FormWrapper";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { FormCheckbox } from "./FormCheckbox";
import { FormFieldset } from "./FormFieldset";
import { FormInput } from "./FormInput";
import { FormRadio } from "./FormRadio";
import { FormRange } from "./FormRange";
import { FormSelect } from "./FormSelect";
import { FormSelectOption } from "./FormSelectOption";
import { FormTextarea } from "./FormTextarea";

/**
 * ContactForm
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ContactForm({
  settingsClasses = " ",
  settingsVisibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={"form_component"}
          tag={"div"}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <FormWrapper className={"form_wrap"}>
            <FormForm
              className={"form_element"}
              data-name={"Contact Form"}
              id={"wf-form-Contact-Form"}
              method={"get"}
              name={"wf-form-Contact-Form"}
            >
              <FormFieldset
                content={
                  <>
                    <FormInput inputType={"First Name"} required={true} />
                    <FormInput inputType={"Last Name"} required={true} />
                    <FormInput
                      customPlaceholder={"email@company.com"}
                      inputType={"Email"}
                      required={true}
                    />
                    <FormFieldset
                      content={
                        <>
                          <FormSelect
                            formSelectOption={
                              <>
                                <FormSelectOption
                                  text={"Select one..."}
                                  value={""}
                                />
                                <FormSelectOption
                                  selectedByDefault={false}
                                  text={"Option 1"}
                                  value={"Option 1"}
                                />
                                <FormSelectOption
                                  text={"Option 2"}
                                  value={"Option 2"}
                                />
                                <FormSelectOption
                                  text={"Option 3"}
                                  value={"Option 3"}
                                />
                              </>
                            }
                            label={"State"}
                            settingsWrapperAttributes={{
                              class: "u-column-span-2",
                            }}
                          />
                          <FormInput inputType={"Zip Code"} />
                        </>
                      }
                      layout={"Grid 3 Column"}
                      legendStyle={"Hidden"}
                      text={"Address"}
                    />
                    <FormFieldset
                      content={
                        <>
                          <FormSelect
                            formSelectOption={
                              <>
                                <FormSelectOption text={"MM"} value={""} />
                                <FormSelectOption
                                  text={"January"}
                                  value={"January"}
                                />
                                <FormSelectOption
                                  text={"February"}
                                  value={"February"}
                                />
                                <FormSelectOption
                                  text={"March"}
                                  value={"March"}
                                />
                                <FormSelectOption
                                  text={"April"}
                                  value={"April"}
                                />
                                <FormSelectOption text={"May"} value={"May"} />
                                <FormSelectOption
                                  text={"June"}
                                  value={"June"}
                                />
                                <FormSelectOption
                                  text={"July"}
                                  value={"July"}
                                />
                                <FormSelectOption
                                  text={"August"}
                                  value={"August"}
                                />
                                <FormSelectOption
                                  text={"September"}
                                  value={"September"}
                                />
                                <FormSelectOption
                                  text={"October"}
                                  value={"October"}
                                />
                                <FormSelectOption
                                  text={"November"}
                                  value={"November"}
                                />
                                <FormSelectOption
                                  text={"December"}
                                  value={"December"}
                                />
                              </>
                            }
                            label={"Month"}
                            settingsLabelStyle={"Hidden"}
                          />
                          <FormSelect
                            formSelectOption={
                              <>
                                <FormSelectOption text={"DD"} value={""} />
                                <FormSelectOption text={"1"} value={"1"} />
                                <FormSelectOption text={"2"} value={"2"} />
                                <FormSelectOption text={"3"} value={"3"} />
                              </>
                            }
                            label={"Day"}
                            settingsLabelStyle={"Hidden"}
                          />
                          <FormSelect
                            formSelectOption={
                              <>
                                <FormSelectOption text={"YYYY"} value={""} />
                                <FormSelectOption
                                  text={"2025"}
                                  value={"2025"}
                                />
                                <FormSelectOption
                                  text={"2024"}
                                  value={"2024"}
                                />
                                <FormSelectOption
                                  text={"2023"}
                                  value={"2023"}
                                />
                              </>
                            }
                            label={"Year"}
                            settingsLabelStyle={"Hidden"}
                          />
                        </>
                      }
                      layout={"Grid 3 Column"}
                      text={"Date of Birth"}
                    />
                    <FormInput
                      customPlaceholder={"000-000-0000"}
                      inputType={"Phone"}
                    />
                  </>
                }
                layout={"Grid 2 Column"}
                legendStyle={"Bold"}
                text={"Contact Details"}
              />
              <FormFieldset
                content={
                  <>
                    <FormFieldset
                      content={
                        <>
                          <FormRadio
                            groupName={"Color"}
                            label={"Red"}
                            settingsRole={false}
                          />
                          <FormRadio
                            groupName={"Color"}
                            label={"Green"}
                            settingsRole={false}
                          />
                          <FormRadio
                            groupName={"Color"}
                            label={"Blue"}
                            settingsRole={false}
                          />
                        </>
                      }
                      layout={"Flex Horizontal"}
                      settingsSlotRole={false}
                      text={"Favorite Color"}
                    />
                    <FormFieldset
                      content={
                        <>
                          <FormCheckbox
                            checked={true}
                            label={"I agree to the terms"}
                            settingsRole={false}
                          />
                          <FormCheckbox
                            label={"I agree to the terms"}
                            settingsRole={false}
                          />
                        </>
                      }
                      layout={"Flex Horizontal"}
                      settingsSlotRole={false}
                      text={"Terms & Conditions"}
                    />
                    <FormSelect
                      formSelectOption={
                        <>
                          <FormSelectOption text={"Select one..."} value={""} />
                          <FormSelectOption />
                          <FormSelectOption
                            text={"Option 2"}
                            value={"Option 2"}
                          />
                          <FormSelectOption
                            text={"Option 3"}
                            value={"Option 3"}
                          />
                        </>
                      }
                      label={"Job Title"}
                    />
                    <FormInput
                      customLabel={"Completion Date"}
                      customPlaceholder={""}
                      inputType={"Date"}
                    />
                    <FormRange />
                    <FormTextarea
                      label={"Message"}
                      placeholder={"Your message"}
                      required={true}
                    />
                  </>
                }
                layout={"Grid 2 Column"}
                legendStyle={"Bold"}
              />
              <ButtonWrapper
                content={
                  <ButtonMain settingsButtonType={false} text={"Submit"} />
                }
                marginTop={0}
              />
            </FormForm>
            <FormSuccessMessage className={"form_success_wrap"}>
              <Block className={"form_success_text"} tag={"div"}>
                {"Thank you! Your submission has been received!"}
              </Block>
            </FormSuccessMessage>
            <FormErrorMessage className={"form_error_wrap"}>
              <Block className={"form_error_text"} tag={"div"}>
                {"Oops! Something went wrong while submitting the form."}
              </Block>
            </FormErrorMessage>
          </FormWrapper>
        </DOM>
      ) : null}
    </div>
  );
}
