/**
 * @generated
 * @file EmailForm (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import FormErrorMessage from "../webflow_modules/Form/components/FormErrorMessage";
import FormForm from "../webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "../webflow_modules/Form/components/FormSuccessMessage";
import FormWrapper from "../webflow_modules/Form/components/FormWrapper";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { FormFieldset } from "./FormFieldset";
import { FormInput } from "./FormInput";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";

/**
 * EmailForm
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function EmailForm({
  form = true,
  settingsClasses = " ",
  settingsVisibility = true,
  theme = "Light",
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    "Max Width": "w-variant-57681fca-5df7-60c4-87e7-711ecca8ed3b",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`form_component ${_activeStyleVariant}`}
          tag={"div"}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <ThemeSwitcher theme={theme} />
          {form ? (
            <FormWrapper className={`form_wrap ${_activeStyleVariant}`}>
              <FormForm
                className={`form_element is-block ${_activeStyleVariant}`}
                data-name={"Book a demo"}
                id={"wf-form-Book-a-demo"}
                method={"get"}
                name={"wf-form-Book-a-demo"}
                {...{
                  [theme !== "Square" ? "class" : ""]:
                    theme === "Light"
                      ? "u-theme-light"
                      : theme === "Grey"
                      ? "u-theme-dark"
                      : theme === "Brand"
                      ? "u-theme-brand"
                      : "",
                }}
              >
                <Block
                  className={`form_fieldset_placement ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <FormFieldset
                    content={
                      <FormInput
                        customLabel={"Email"}
                        customPlaceholder={"What's your work email?"}
                        inputType={"Email"}
                        required={true}
                        settingsLabelVariant={"Hidden"}
                        settingsSubmissionName={"work-email"}
                      />
                    }
                    legendStyle={"Hidden"}
                    text={"Book a Demo"}
                  />
                </Block>
                <ButtonWrapper
                  content={<ButtonMain settingsButtonType={false} />}
                  marginTop={0}
                  variant={"Grow"}
                />
              </FormForm>
              <FormSuccessMessage
                className={`form_success_wrap ${_activeStyleVariant}`}
              >
                <Block
                  className={`form_success_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Thank you! Your submission has been received!"}
                </Block>
              </FormSuccessMessage>
              <FormErrorMessage
                className={`form_error_wrap ${_activeStyleVariant}`}
              >
                <Block
                  className={`form_error_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Oops! Something went wrong while submitting the form."}
                </Block>
              </FormErrorMessage>
            </FormWrapper>
          ) : null}
          {!form ? (
            <FormWrapper className={`form_wrap ${_activeStyleVariant}`}>
              <FormForm
                className={`form_element is-block ${_activeStyleVariant}`}
                data-name={"Join newsletter"}
                id={"wf-form-Join-newsletter"}
                method={"get"}
                name={"wf-form-Join-newsletter"}
                {...{
                  [theme !== "Square" ? "class" : ""]:
                    theme === "Light"
                      ? "u-theme-light"
                      : theme === "Grey"
                      ? "u-theme-dark"
                      : theme === "Brand"
                      ? "u-theme-brand"
                      : "",
                }}
              >
                <Block
                  className={`form_fieldset_placement ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <FormFieldset
                    content={
                      <FormInput
                        customLabel={"Email"}
                        customPlaceholder={"What's your work email?"}
                        inputType={"Email"}
                        required={true}
                        settingsLabelVariant={"Hidden"}
                        settingsSubmissionName={"work-email"}
                      />
                    }
                    legendStyle={"Hidden"}
                    text={"Book a Demo"}
                  />
                </Block>
                <ButtonWrapper
                  content={
                    <ButtonMain settingsButtonType={false} text={"Subscribe"} />
                  }
                  marginTop={0}
                  variant={"Grow"}
                />
              </FormForm>
              <FormSuccessMessage
                className={`form_success_wrap ${_activeStyleVariant}`}
              >
                <Block
                  className={`form_success_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Thank you! Your submission has been received!"}
                </Block>
              </FormSuccessMessage>
              <FormErrorMessage
                className={`form_error_wrap ${_activeStyleVariant}`}
              >
                <Block
                  className={`form_error_text ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"Oops! Something went wrong while submitting the form."}
                </Block>
              </FormErrorMessage>
            </FormWrapper>
          ) : null}
        </DOM>
      ) : null}
    </div>
  );
}
