/**
 * @generated
 * @file FormCheckbox (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { CheckUi } from "../miscellaneous/CheckUi";
import { listOfElementsToText } from "../webflow_modules/Basic/helpers/listOfElementsToText";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FormCheckbox
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormCheckbox({
  checked = false,
  label = "Field Label",
  required = false,
  settingsInputAttributes = {},
  settingsLabelAttributes = {},
  settingsRole = false,
  settingsSubmissionName = "",
  settingsVisibility = true,
  settingsWrapperAttributes = {},
  style = "Checkbox",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !!toText(label) ? (
        <DOM className={"form_ui_item"} tag={"div"}>
          <CheckUi
            checked={checked}
            label={label}
            name={
              settingsSubmissionName !== ""
                ? settingsSubmissionName
                : listOfElementsToText(label)
            }
            required={required}
            settingsInputAttributes={{
              ...settingsInputAttributes,
            }}
            settingsLabelAttributes={{
              ...settingsLabelAttributes,
            }}
            settingsVariant={style}
            value={""}
          />
        </DOM>
      ) : null}
    </div>
  );
}
