/**
 * @generated
 * @file FormTextarea (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { FormLabelText } from "./FormLabelText";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FormTextarea
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormTextarea({
  defaultValue = "",
  label = "Label",
  placeholder = "",
  required = false,
  settingsLabelVariant = "Visible",
  settingsSubmissionName = "",
  settingsTextareaAttributes = {},
  settingsVisibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !!toText(label) ? (
        <DOM className={"form_label_wrap"} data-trigger={"focus"} tag={"label"}>
          <FormLabelText
            settingsRequired={required}
            text={label}
            variant={settingsLabelVariant}
          />
          <DOM className={"form_field is-textarea"} tag={"textarea"} />
        </DOM>
      ) : null}
    </div>
  );
}
