/**
 * @generated
 * @file FormFieldset (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { FormLabelText } from "./FormLabelText";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FormFieldset
 *
 * Holds Checkbox or Radio elements
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormFieldset({
  content,
  layout = "Flex Vertical",
  legendStyle = "Visible",
  settingsSlotRole = false,
  settingsVisibility = true,
  settingsWrapperAttributes = {},
  text = "Legend",
}) {
  const _styleVariantMap = {
    "Flex Vertical": "",
    "Flex Horizontal": "w-variant-ccbf2df7-16d0-30d7-0afb-0df098785596",
    "Grid 2 Column": "w-variant-14c165fa-7397-02ef-8dc0-6e307b6c980f",
    "Grid 3 Column": "w-variant-5fdb0361-c340-58a0-00d3-b0e0b17257ad",
  };

  const _activeStyleVariant = _styleVariantMap[layout];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !!toText(text) ? (
        <DOM
          className={`form_fieldset_wrap ${_activeStyleVariant}`}
          tag={"fieldset"}
        >
          <FormLabelText
            settingsTag={"legend"}
            text={text}
            variant={legendStyle}
          />
          {content}
          <HtmlEmbed
            className={`u-embed-css ${_activeStyleVariant}`}
            content={
              "<style>\n@container (width < 40em) {\n\t.form_fieldset_list:has(.form_fieldset_list) { display: flex; }\n}\n@container (width < 18em) {\n\t.form_fieldset_list { display: flex; }\n}\n</style>"
            }
          />
        </DOM>
      ) : null}
    </div>
  );
}
