/**
 * @generated
 * @file FormSelect (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { FormLabelText } from "./FormLabelText";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FormSelect
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormSelect({
  formSelectOption,
  label = "Label",
  required = false,
  settingsAllowMultiSelect = false,
  settingsLabelStyle = "Visible",
  settingsSelectAttributes = {},
  settingsSubmissionName = "",
  settingsVisibility = true,
  settingsWrapperAttributes = {},
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !!toText(label) ? (
        <DOM className={"form_label_wrap"} tag={"label"}>
          <FormLabelText
            settingsRequired={required}
            text={label}
            variant={settingsLabelStyle}
          />
          <DOM className={"form_select_wrap"} tag={"span"}>
            <DOM className={"form_field"} tag={"select"}>
              {formSelectOption}
            </DOM>
            <DOM
              aria-hidden={"true"}
              className={"form_select_icon"}
              fill={"none"}
              tag={"svg"}
              viewBox={"0 0 6 5"}
              width={"100%"}
            >
              <DOM
                d={"M0.5 1L3 3.5L5.5 1"}
                stroke={"currentColor"}
                strokeWidth={"0.125rem"}
                tag={"path"}
                vectorEffect={"non-scaling-stroke"}
              />
            </DOM>
          </DOM>
        </DOM>
      ) : null}
    </div>
  );
}
