/**
 * @generated
 * @file FormLabelText (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * FormLabelText
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormLabelText({
  settingsClasses = "",
  settingsRequired = false,
  settingsTag = "span",
  settingsVisibility = true,
  text = "Label",
  variant = "Visible",
}) {
  const _styleVariantMap = {
    Visible: "",
    Hidden: "w-variant-46933b79-cf19-81b4-bc00-8af5c19b08b3",
    Bold: "w-variant-e8e97384-daa0-7ce7-bc12-14efcd69bcd4",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`form_label_text ${_activeStyleVariant}`}
          tag={settingsTag}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <DOM tag={"span"}>{text}</DOM>
          {settingsRequired ? <DOM tag={"span"}>{"*"}</DOM> : null}
        </DOM>
      ) : null}
    </div>
  );
}
