/**
 * @generated
 * @file FormRange (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { FormLabelText } from "./FormLabelText";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FormRange
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormRange({
  id = "field-id",
  label = "Label",
  max = 100,
  min = 0,
  outputUnit = "%",
  required = false,
  settingsInputAttributes = {},
  settingsLabelVariant = "Visible",
  settingsSubmissionName = "",
  settingsVisibility = true,
  step = 1,
  value = 50,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={"form_range_wrap"}
          data-default-value={formatNumber(-1)(value)}
          tag={"div"}
        >
          <HtmlEmbed
            className={"u-embed-css"}
            content={
              '<style>\n.form_range_wrap {\n\t--progress: 0.5;\n  --thumb-size: 2rem;\n  --thumb-radius: 100vw;\n  --thumb-color: transparent;\n}\ninput[type="range"] {\n\tappearance: none;\n}\ninput[type="range"]::-webkit-slider-thumb {\n\tcursor: grab;\n  appearance: none;\n  width: var(--thumb-size);\n  aspect-ratio: 1 / 1;\n  border-radius: var(--thumb-radius);\n  background: var(--thumb-color);\n}\ninput[type="range"]::-moz-range-thumb {\n\tcursor: grab;\n  appearance: none;\n  width: var(--thumb-size);\n  aspect-ratio: 1 / 1;\n  border-radius: var(--thumb-radius);\n  background: var(--thumb-color);\n}\ninput[type="range"]::-webkit-slider-thumb:active {\n  cursor: grabbing;\n}\ninput[type="range"]::-moz-range-thumb:active {\n  cursor: grabbing;\n}\n</style>\n\n<noscript><style>\n.form_range_wrap { --thumb-color: currentColor; }\n.form_range_fill, .form_range_thumb_wrap { display: none; }\n</style></noscript>'
            }
          />
          <DOM className={"form_label_wrap"} tag={"label"}>
            <FormLabelText
              settingsRequired={required}
              text={label}
              variant={settingsLabelVariant}
            />
            <DOM className={"form_range_element"} tag={"span"}>
              <DOM className={"form_range_input"} tag={"input"} />
              <DOM className={"form_range_fill"} tag={"span"} />
              <DOM className={"form_range_thumb_wrap"} tag={"span"}>
                <DOM className={"form_range_thumb_element"} tag={"span"} />
              </DOM>
            </DOM>
          </DOM>
          <DOM className={"form_range_output_wrap"} tag={"span"}>
            <DOM
              className={"form_range_output_element"}
              tag={"ouput"}
              {...{
                [id !== "" ? "for" : ""]: id,
              }}
            >
              <DOM className={"form_range_output_value"} tag={"span"}>
                {formatNumber(-1)(value)}
              </DOM>
              {!!toText(outputUnit) ? (
                <DOM tag={"span"}>{outputUnit}</DOM>
              ) : null}
            </DOM>
          </DOM>
          <HtmlEmbed
            className={"u-embed-js"}
            content={
              '<script>\n(function() {\n  const component = document.currentScript.parentElement.parentElement;\n  document.addEventListener("DOMContentLoaded", () => {\n    const input = component.querySelector("input[type=\'range\']");\n    const output = component.querySelector(".form_range_output_value");\n\n    const update = () => {\n      const min = input.min ? +input.min : 0;\n      const max = input.max ? +input.max : 100;\n      const val = +input.value || min;\n      const progress = (val - min) / (max - min);\n      component.style.setProperty("--progress", progress);\n      if (output) output.textContent = val;\n    };\n    input.addEventListener("input", update);\n    update();\n  });\n})();\n</script>'
            }
          />
        </DOM>
      ) : null}
    </div>
  );
}
