/**
 * @generated
 * @file FormRadio (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { CheckUi } from "../miscellaneous/CheckUi";
import { listOfElementsToText } from "../webflow_modules/Basic/helpers/listOfElementsToText";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FormRadio
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormRadio({
  checked = false,
  groupName = "Group Name",
  label = "Label",
  required = false,
  settingsClasses = "",
  settingsInputAttributes = {},
  settingsLabelAttributes = {},
  settingsRole = false,
  settingsSubmissionValue = "",
  settingsVisibility = true,
  style = "Radio",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !!toText(label) ? (
        <DOM
          className={`form_ui_item ${settingsClasses}`}
          data-state={"checked"}
          role={settingsRole ? "none" : "listitem"}
          tag={"div"}
        >
          <CheckUi
            checked={checked}
            label={label}
            name={groupName}
            required={required}
            settingsInputAttributes={{
              ...settingsInputAttributes,
            }}
            settingsLabelAttributes={{
              ...settingsLabelAttributes,
            }}
            settingsVariant={style}
            type={false}
            value={
              settingsSubmissionValue !== ""
                ? settingsSubmissionValue
                : listOfElementsToText(label)
            }
          />
        </DOM>
      ) : null}
    </div>
  );
}
