/**
 * @generated
 * @file FormSelectOption (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * FormSelectOption
 *
 * This goes inside a select element.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormSelectOption({
  selectedByDefault = false,
  settingsHidden = false,
  settingsVisibility = true,
  text = "Option 1",
  value = "Option 1",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          tag={"option"}
          value={value}
          {...{
            [selectedByDefault ? "selected" : ""]: " ",
            [settingsHidden ? "hidden" : ""]: " ",
          }}
        >
          {text}
        </DOM>
      ) : null}
    </div>
  );
}
