/**
 * @generated
 * @file FormInput (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { FormLabelText } from "./FormLabelText";
import { InputSwitcher } from "../variantSwitcher/InputSwitcher";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * FormInput
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FormInput({
  customLabel = "",
  customPlaceholder = "",
  defaultValue = "",
  inputType = "Text",
  required = false,
  settingsInputAttributes = {},
  settingsLabelVariant = "Visible",
  settingsSubmissionName = "",
  settingsVisibility = true,
  settingsWrapperAttributes = {},
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM className={"form_label_wrap"} tag={"label"}>
          <FormLabelText
            settingsRequired={required}
            text={
              !!toText(customLabel)
                ? customLabel
                : inputType === "First Name"
                ? ["First Name"]
                : inputType === "Last Name"
                ? ["Last Name"]
                : inputType === "Email"
                ? ["Email Address"]
                : inputType === "Phone"
                ? ["Phone Number"]
                : inputType === "Date"
                ? ["Date"]
                : inputType === "Search"
                ? ["Search"]
                : inputType === "Password"
                ? ["Password"]
                : inputType === "URL"
                ? ["Website"]
                : inputType === "Number"
                ? ["Number"]
                : inputType === "Zip Code"
                ? ["Zip Code"]
                : ["Label"]
            }
            variant={settingsLabelVariant}
          />
          <DOM className={"form_field"} tag={"input"} />
          <InputSwitcher variant={inputType} />
        </DOM>
      ) : null}
    </div>
  );
}
