/**
 * @generated
 * @file PhosphorIcon (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * PhosphorIcon
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function PhosphorIcon({
  classProp = "ph-x",
  variant = "Medium",
  visibility = true,
}) {
  const _styleVariantMap = {
    Small: "w-variant-5675a1ec-43b6-3dee-6fd6-da05aaabccbb",
    Medium: "",
    Large: "w-variant-56580b32-38fd-c2ee-f313-9cbc7f07c517",
    Huge: "w-variant-4e546c0e-4523-130a-2e06-904f97c092da",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={`ph-wrap ${_activeStyleVariant}`} tag={"div"}>
          <DOM className={`ph ${classProp} ${_activeStyleVariant}`} tag={"i"} />
        </Block>
      ) : null}
    </div>
  );
}
