/**
 * @generated
 * @file PlainHeading (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Heading from "../webflow_modules/Basic/components/Heading";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * PlainHeading
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function PlainHeading({
  classes = "",
  id = "",
  maxWidth = 20,
  tag = "h2",
  title = "Heading",
  variant = "Inherit",
  visibility = true,
}) {
  const _styleVariantMap = {
    Inherit: "",
    Display: "w-variant-0ffe5876-2bc6-f6c2-53cc-a7a8a2bb96f0",
    H1: "w-variant-564d5a94-f47f-9a47-60eb-78f99f2dd2ff",
    H2: "w-variant-c2db510d-5566-fc00-e8ec-7b7b8271aa92",
    H3: "w-variant-a4809fdc-4884-c670-a420-a7b6d3ff712c",
    H4: "w-variant-f0d17f33-69f4-9ad4-b464-12972f7168cf",
    H5: "w-variant-dd3512ad-5583-9a25-4502-3eb317ec0778",
    H6: "w-variant-26e27ea1-31e7-8f3b-4889-2d01ab3cb3cd",
    "Text Large": "w-variant-7f6f7603-1a13-e29b-e8a8-c448f692863d",
    "Text Main": "w-variant-100aecc5-e659-4022-10fb-accc4e82c33c",
    "Text Small": "w-variant-b3fe49ac-de90-68e9-cf96-5e8b750d7e74",
    "Text XSmall": "w-variant-564a35b4-2f58-703e-fca1-7c75391147e4",
    "Text Eyebrow": "w-variant-c268d842-29f0-c686-968a-cb14d4cc9078",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Heading
          className={`u-heading-plain ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(maxWidth)}
          id={id}
          tag={tag}
          {...{
            [classes !== "" ? "class" : ""]: classes,
          }}
        >
          {title}
        </Heading>
      ) : null}
    </div>
  );
}
