/**
 * @generated
 * @file SpanGroup (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * SpanGroup
 *
 * Wrapper for multiple spans. Used for adding popover triggers and surrounding text. Can adjust the style and tag.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function SpanGroup({ span, tag = "p" }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block tag={"div"}>
        <DOM className={"u-text"} tag={tag}>
          {span}
        </DOM>
      </Block>
    </div>
  );
}
