/**
 * @generated
 * @file Tag (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { PhosphorIcon } from "./PhosphorIcon";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { TypographyPlain } from "./TypographyPlain";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { conditional } from "../webflow_modules/Conditionals/helpers/conditional";
import { equals } from "../webflow_modules/Number/helpers/equals";
import { every } from "../webflow_modules/Boolean/helpers/every";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * Tag
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Tag({
  attributes = {},
  classes = "",
  id = "",
  marginBottom = -1,
  phosphorIconClass = "ph-x",
  phosphorIconVariant = "Medium",
  phosphorIconVisibility = true,
  text = "Tag text",
  theme = "Inherit",
  variant = "Small",
  visibility = true,
}) {
  const _styleVariantMap = {
    XSmall: "w-variant-f3aa24c7-53e4-9ead-777f-5546c685a725",
    Small: "",
    Medium: "w-variant-48ef500c-89df-10a1-3c12-e4d08f64eae0",
    Pill: "w-variant-1dbe4fba-f25a-8ff5-32b2-1e7c4bbb5f37",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          className={`tag_wrap ${conditional({
            rules: [
              {
                condition: every([applyPredicate(marginBottom)(equals(-1))]),
                output: "u-margin-bottom-4",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(0))]),
                output: "u-margin-bottom-0",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(1))]),
                output: "u-margin-bottom-1",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(2))]),
                output: "u-margin-bottom-2",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(3))]),
                output: "u-margin-bottom-3",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(4))]),
                output: "u-margin-bottom-4",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(5))]),
                output: "u-margin-bottom-5",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(6))]),
                output: "u-margin-bottom-6",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(7))]),
                output: "u-margin-bottom-7",
              },
              {
                condition: every([applyPredicate(marginBottom)(equals(8))]),
                output: "u-margin-bottom-8",
              },
            ],

            fallback: "",
          })} ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(marginBottom)}
          data-tag-id={id}
          tag={"div"}
          {...{
            [classes !== "" ? "class" : ""]: classes,
            [theme !== "Square" ? "class" : ""]:
              theme === "Light"
                ? "u-theme-light"
                : theme === "Grey"
                ? "u-theme-grey"
                : theme === "Brand"
                ? "u-theme-brand"
                : theme === "Accent1"
                ? "u-theme-accent1"
                : theme === "Accent2"
                ? "u-theme-accent2"
                : theme === "Dark"
                ? "u-theme-dark"
                : "",
          }}
          {...attributes}
        >
          {phosphorIconVisibility ? (
            <Block className={`tag_icon ${_activeStyleVariant}`} tag={"div"}>
              <PhosphorIcon
                classProp={phosphorIconClass}
                variant={"Medium"}
                visibility={phosphorIconVisibility}
              />
            </Block>
          ) : null}
          <TypographyPlain
            marginBottom={0}
            settingsAttributes={""}
            text={text}
            variant={
              ["Inherit", "XSmall"].includes(variant)
                ? "Text XSmall"
                : variant === "Medium"
                ? "Text Small"
                : variant === "Pill"
                ? "Text Eyebrow"
                : "Inherit"
            }
          />
          <ThemeSwitcher theme={theme} />
        </Block>
      ) : null}
    </div>
  );
}
