/**
 * @generated
 * @file TextWPopover (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * TextWPopover
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TextWPopover({
  maxWidth = 60,
  popoverTarget,
  tag = "h2",
  text,
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Eyebrow: "w-variant-da6cd92d-943f-6d03-91e3-d1cf1ef886b9",
    "Text XSmall": "w-variant-23a6720e-196e-88b1-fdeb-51a0ea41ac2f",
    "Text Small": "w-variant-ad69d9e3-0a18-94bc-8a29-530060e54fba",
    "Text Large": "w-variant-120774c7-33cc-79f3-1e3e-e83051742407",
    H6: "w-variant-ce3de837-8095-dab6-baa3-3725285fe91d",
    H5: "w-variant-f326bd62-f009-fdfa-2c8d-5e365cdd520d",
    H4: "w-variant-4692e22d-e73b-5621-8469-098f1ae23d75",
    H3: "w-variant-4071dac0-faae-f09b-7bd3-8194ecd05981",
    H2: "w-variant-b794346d-5079-4ec2-0a4e-d80420d262fc",
    H1: "w-variant-318c78d3-df0a-b862-71f5-b06431a13dfe",
    Display: "w-variant-e94adcf7-1d5d-073b-20d6-d3b2fd05abb3",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`popover_wrap ${_activeStyleVariant}`} tag={"div"}>
        {popoverTarget}
        <DOM
          className={`u-text-plain ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(maxWidth)}
          tag={tag}
        >
          {text}
        </DOM>
      </Block>
    </div>
  );
}
