/**
 * @generated
 * @file TypographyHeading (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import RichText from "../webflow_modules/Basic/components/RichText";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * TypographyHeading
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TypographyHeading({
  marginBottom = -1,
  maxWidth = 20,
  settingsAttributes = {},
  settingsClasses = "",
  settingsId = "",
  settingsVisibility = false,
  text = "",
  tidyText = false,
  variant = "H2",
}) {
  const _styleVariantMap = {
    Inherit: "",
    Eyebrow: "w-variant-db9a5ab0-1099-e983-08cf-c9d0a83a2fa1",
    "Text XSmall": "w-variant-a1ad5421-4390-0dc7-6654-e307dc9ac06b",
    "Text Small": "w-variant-3fbd0d32-5675-1947-73b3-abb16c1fb986",
    "Text Main": "w-variant-9027c8ae-1ba5-f702-ea6e-4a1c3fca9f64",
    "Text Large": "w-variant-74a3180a-e505-b452-032f-599c8e557249",
    H6: "w-variant-823daff2-fd84-8da0-4ed1-92a39b869ad0",
    H5: "w-variant-326a9562-3263-06da-e8ef-16981fd70f1c",
    H4: "w-variant-7c7eb163-b37d-338d-2369-5eae7e6d458a",
    H3: "w-variant-701c4b6c-37cf-de59-d80d-80a1822c4994",
    H2: "w-variant-433d40c6-c261-f13f-c899-61d2cadf150f",
    H1: "w-variant-792802b6-ccdb-f982-5023-5fa970cf03d0",
    Display: "w-variant-41c609dc-9c80-9eef-75df-03bf0eea00b4",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!!toText(text) && settingsVisibility ? (
        <RichText
          className={`u-heading ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(maxWidth)}
          id={settingsId}
          tag={"div"}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
            [!tidyText ? "class" : ""]: !tidyText ? "u-text-wrap-default" : "",
            [marginBottom !== -1 ? "class" : ""]:
              marginBottom === 0
                ? "u-margin-bottom-0"
                : marginBottom === 1
                ? "u-margin-bottom-1"
                : marginBottom === 2
                ? "u-margin-bottom-2"
                : marginBottom === 3
                ? "u-margin-bottom-3"
                : marginBottom === 4
                ? "u-margin-bottom-4"
                : marginBottom === 5
                ? "u-margin-bottom-5"
                : marginBottom === 6
                ? "u-margin-bottom-6"
                : marginBottom === 7
                ? "u-margin-bottom-7"
                : marginBottom === 8
                ? "u-margin-bottom-8"
                : "",
          }}
          {...settingsAttributes}
        >
          {text}
        </RichText>
      ) : null}
    </div>
  );
}
