/**
 * @generated
 * @file TypographyTag (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * TypographyTag
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TypographyTag({
  settingsAttributes = {},
  settingsVisibility = true,
  text = "Text Block",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM className={"tag_wrap"} tag={"div"}>
          {text}
        </DOM>
      ) : null}
    </div>
  );
}
