/**
 * @generated
 * @file TypographyParagraph (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import RichText from "../webflow_modules/Basic/components/RichText";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * TypographyParagraph
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TypographyParagraph({
  colour = true,
  marginBottom = -1,
  maxWidth = 60,
  settingsAttributes = {},
  settingsClasses = " ",
  settingsVisibility = false,
  text = "",
  tidyText = false,
  variant = "Inherit",
}) {
  const _styleVariantMap = {
    Inherit: "",
    "Text XXSmall": "w-variant-3898dde6-1d81-7bb7-0e5d-1ead31a90dee",
    "Text XSmall": "w-variant-5c70b067-e22d-e98f-1562-5557e3ac21d9",
    "Text Small": "w-variant-4099173f-f581-635c-a5fe-cf4a89c62029",
    "Text Main": "w-variant-61d538b2-709c-eb7a-4258-8c0890dc07fc",
    "Text Large": "w-variant-fdb8e663-01e0-aae6-13eb-e6dfca16b689",
    H6: "w-variant-b8555f10-fa7d-e9ba-e262-f9aa44c27c1c",
    H5: "w-variant-5c484503-e2a0-ac99-680d-56013d859efa",
    H4: "w-variant-93e8af18-8413-e3ac-0442-72629401a3db",
    H3: "w-variant-ad482112-9d0e-852c-0f6e-ba1e5a3aee59",
    H2: "w-variant-efb733fe-da83-69a3-ea4a-b3f2f89d0389",
    H1: "w-variant-3ddfa43e-abc1-422e-6e6d-23dfb7da71f3",
    Display: "w-variant-eee56f15-d7ce-d101-2f8c-83b3bbd55d4a",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!!toText(text) && settingsVisibility ? (
        <RichText
          className={`u-text u-rich-text ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(maxWidth)}
          tag={"div"}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
            [!tidyText ? "class" : ""]: !tidyText ? "u-text-wrap-default" : "",
            [marginBottom !== -1 ? "class" : ""]:
              marginBottom === 0
                ? "u-margin-bottom-0"
                : marginBottom === 1
                ? "u-margin-bottom-1"
                : marginBottom === 2
                ? "u-margin-bottom-2"
                : marginBottom === 3
                ? "u-margin-bottom-3"
                : marginBottom === 4
                ? "u-margin-bottom-4"
                : marginBottom === 5
                ? "u-margin-bottom-5"
                : marginBottom === 6
                ? "u-margin-bottom-6"
                : marginBottom === 7
                ? "u-margin-bottom-7"
                : marginBottom === 8
                ? "u-margin-bottom-8"
                : "",
            [!colour ? "class" : ""]: !colour ? "u-faded" : "",
          }}
          {...settingsAttributes}
        >
          {text}
        </RichText>
      ) : null}
    </div>
  );
}
