/**
 * @generated
 * @file TypographyPlain (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * TypographyPlain
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TypographyPlain({
  marginBottom = -1,
  maxWidth = -1,
  settingsAttributes = {},
  settingsStyle = "",
  settingsTag = "p",
  settingsVisibility = false,
  text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  variant = "Inherit",
}) {
  const _styleVariantMap = {
    Inherit: "",
    "Text Eyebrow": "w-variant-56e21c8d-0820-3b40-d732-181889663223",
    "Text XSmall": "w-variant-bf8ee17c-e768-69d7-44c9-2840e77be33c",
    "Text Small": "w-variant-fe6f474d-1651-566b-eeff-3c86e8cbf153",
    "Text Main": "w-variant-26cc9f23-e71c-deee-cd61-36dc24f35fae",
    "Text Large": "w-variant-c8b8ac88-1ac7-e9f6-41cc-82c548bf142d",
    H6: "w-variant-47e40b0d-02af-2673-f429-546cac42dc5a",
    H5: "w-variant-12e93187-f8ac-b1a1-2e50-59d85a6bf516",
    H4: "w-variant-f196774e-dbfd-d1b4-1196-b3e824fc5f7d",
    H3: "w-variant-7bfbf33b-fb56-d8df-e2d2-8fe65a7f2e44",
    H2: "w-variant-9af60b09-c3a1-8c2a-eb78-8e29460ca7a9",
    H1: "w-variant-83c598b0-8cc2-f955-1996-fcb8fb10bf70",
    Display: "w-variant-8ee37a78-065b-6879-973d-319c65e28313",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!!toText(text) && settingsVisibility ? (
        <DOM
          className={`u-text-plain ${_activeStyleVariant}`}
          tag={settingsTag}
        >
          {text}
        </DOM>
      ) : null}
    </div>
  );
}
