/**
 * @generated
 * @file TypographyEyebrow (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import RichText from "../webflow_modules/Basic/components/RichText";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * TypographyEyebrow
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TypographyEyebrow({
  marginBottom = -1,
  settingsAttributes = {},
  settingsVisibility = false,
  text = "",
  textVisibility = true,
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Display: "w-variant-ac49f9fc-2f83-32f5-ced8-912b503c27e9",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!!toText(text) && settingsVisibility ? (
        <DOM className={`u-eyebrow-wrapper ${_activeStyleVariant}`} tag={"div"}>
          <Block
            className={`u-eyebrow-layout ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`u-eyebrow-marker ${_activeStyleVariant}`}
              tag={"div"}
            />
            {textVisibility ? (
              <RichText
                className={`u-eyebrow-text u-text-style-eyebrow ${_activeStyleVariant}`}
                tag={"div"}
              >
                {text}
              </RichText>
            ) : null}
          </Block>
        </DOM>
      ) : null}
    </div>
  );
}
