/**
 * @generated
 * @file ButtonAction (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { Clickable } from "../utility/Clickable";
import { PhosphorIcon } from "../typography/PhosphorIcon";

/**
 * ButtonAction
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ButtonAction({
  link = {
    href: "#",
  },

  phosphorIconClass = "ph-x",
  settingsAttributes = {},
  settingsClasses = "",
  settingsVisibility = false,
  text = "Close",
  variant = "Primary / Medium",
}) {
  const _styleVariantMap = {
    "Primary / Medium": "",
    "Secondary / Medium": "w-variant-c144d67f-2c62-4dbf-0fd8-0b6056b717ec",
    "Primary / Large": "w-variant-7198e0ca-f9f4-9662-3fe9-d7114404c9cb",
    "Secondary / Large": "w-variant-c6d40e5e-3298-1af4-067d-37896ebd2a45",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`button_close_wrap ${settingsClasses} ${_activeStyleVariant}`}
          data-trigger={"hover focus"}
          tag={"div"}
        >
          <Block
            className={`button_close_element ${_activeStyleVariant}`}
            data-button={""}
            tag={"div"}
          >
            <Block
              className={`u-overflow-hidden ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                aria-hidden={"true"}
                className={`button_close_icon ${_activeStyleVariant}`}
                tag={"div"}
              >
                <PhosphorIcon classProp={phosphorIconClass} />
              </Block>
            </Block>
          </Block>
          <Clickable link={link} screenReaderText={text} />
        </DOM>
      ) : null}
    </div>
  );
}
