/**
 * @generated
 * @file ButtonPlay (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { Clickable } from "../utility/Clickable";

/**
 * ButtonPlay
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ButtonPlay({
  link = {
    href: "#",
  },

  settingsAttributes = {},
  settingsClasses = " ",
  settingsPressed = false,
  settingsVisibility = false,
  text = "Play",
  variant = "Primary / Medium",
}) {
  const _styleVariantMap = {
    "Primary / Medium": "",
    "Secondary / Medium": "w-variant-ab355ea0-b722-2f23-3507-f0290f710e57",
    "Primary / Large": "w-variant-d47b6b31-1410-4123-4cbe-47472b6d649d",
    "Secondary / Large": "w-variant-3970b3f9-2fa6-52d8-098a-2260caaa12bb",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`button_toggle_wrap ${settingsClasses} ${_activeStyleVariant}`}
          data-state={"pressed"}
          data-trigger={"hover focus"}
          tag={"div"}
        >
          <Block
            className={`button_toggle_element ${_activeStyleVariant}`}
            data-button={""}
            tag={"div"}
          >
            <Block
              aria-hidden={"true"}
              className={`button_toggle_icon ${_activeStyleVariant}`}
              tag={"div"}
            >
              <HtmlEmbed
                aria-hidden={"true"}
                className={`button_toggle_play u-icon ${_activeStyleVariant}`}
                content={
                  '<svg width="1393" height="1394" viewBox="0 0 1393 1394" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M1271 696.5L280 1393V0L1271 696.5Z" fill="black"/>\n</svg>'
                }
              />
              <HtmlEmbed
                aria-hidden={"true"}
                className={`button_toggle_pause u-icon ${_activeStyleVariant}`}
                content={
                  '<svg width="1277" height="1277" viewBox="0 0 1277 1277" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M1087 0H766V1277H1087V0Z" fill="black"/>\n<path d="M510 0H189V1277H510V0Z" fill="black"/>\n</svg>'
                }
              />
            </Block>
          </Block>
          <Clickable link={link} screenReaderText={text} />
        </DOM>
      ) : null}
    </div>
  );
}
