/**
 * @generated
 * @file ButtonArrow (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { Clickable } from "../utility/Clickable";
import { IconArrowFull } from "../svg/IconArrowFull";

/**
 * ButtonArrow
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ButtonArrow({
  arrowDirection = "Right",

  link = {
    href: "#",
  },

  settingsClasses = "",
  settingsClickableAttributes = {},
  settingsVisibility = false,
  text = "Next",
  variant = "Primary / Medium",
}) {
  const _styleVariantMap = {
    "Primary / Medium": "",
    "Secondary / Medium": "w-variant-bb0688d1-65b6-14b6-81e5-21e2cd39bbda",
    "Primary / Large": "w-variant-d7d7e32c-ac47-de0c-eb2d-07f19dfa19d2",
    "Secondary / Large": "w-variant-6c75cae2-0734-1bbf-191f-bfe0f8ed1797",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`button_arrow_wrap ${_activeStyleVariant}`}
          data-button={""}
          data-trigger={"hover focus"}
          tag={"div"}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <Block
            className={`button_arrow_element ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              aria-hidden={"true"}
              className={`button_arrow_icon ${_activeStyleVariant}`}
              tag={"div"}
            >
              <IconArrowFull variant={arrowDirection} />
            </Block>
          </Block>
          <Clickable link={link} screenReaderText={text} visibility={true} />
        </DOM>
      ) : null}
    </div>
  );
}
