/**
 * @generated
 * @file ButtonMain (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { Clickable } from "../utility/Clickable";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * ButtonMain
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ButtonMain({
  attributes = {},
  icon,
  icon2 = "ph-arrow-right",
  iconVisibility = false,

  link = {
    href: "/book-a-demo",
    preload: "prefetch",
  },

  settingsAttributes = {},
  settingsButtonType = true,
  settingsClickableVisibility = true,
  settingsVisibility = true,
  text = "Book a demo",
  variant = "Primary",
}) {
  const _styleVariantMap = {
    Primary: "",
    Secondary: "w-variant-e85564cd-af30-a478-692b-71732aefb3ab",
    Link: "w-variant-625d5df4-ad91-f7dc-9e2f-2e69f3fd7400",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!!toText(text) && settingsVisibility ? (
        <DOM className={`button_main_wrap ${_activeStyleVariant}`} tag={"div"}>
          <Clickable
            buttonType={settingsButtonType}
            link={link}
            screenReaderText={text}
            visibility={settingsClickableVisibility}
          />
          {["Square", "Secondary"].includes(variant) ? (
            <Block
              className={`button_main_background_wrap ${_activeStyleVariant}`}
              tag={"div"}
            >
              <DOM
                className={`button_main_background_column ${_activeStyleVariant}`}
                style={{
                  "--index": " 2",
                }}
                tag={"div"}
              />
              <DOM
                className={`button_main_background_column ${_activeStyleVariant}`}
                style={{
                  "--index": " 1",
                }}
                tag={"div"}
              />
              <DOM
                className={`button_main_background_column ${_activeStyleVariant}`}
                style={{
                  "--index": " 0",
                }}
                tag={"div"}
              />
              <DOM
                className={`button_main_background_column ${_activeStyleVariant}`}
                style={{
                  "--index": " 1",
                }}
                tag={"div"}
              />
              <DOM
                className={`button_main_background_column ${_activeStyleVariant}`}
                style={{
                  "--index": " 2",
                }}
                tag={"div"}
              />
            </Block>
          ) : null}
          <Block
            className={`button_main_element ${_activeStyleVariant}`}
            data-button={""}
            tag={"div"}
          >
            {!["Square", "Secondary"].includes(variant) ? (
              <Block
                aria-hidden={"true"}
                className={`button_main_text u-text-style-small ${_activeStyleVariant}`}
                tag={"div"}
              >
                {text}
              </Block>
            ) : null}
            {["Square", "Secondary"].includes(variant) ? (
              <Block
                className={`button_main_text_wrap ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`button_main_text_animation is-default ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    aria-hidden={"true"}
                    className={`button_main_text u-text-style-small ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    {text}
                  </Block>
                </Block>
                <Block
                  aria-hidden={"true"}
                  className={`button_main_text_animation is-hover ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    aria-hidden={"true"}
                    className={`button_main_text u-text-style-small ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    {text}
                  </Block>
                </Block>
              </Block>
            ) : null}
            {variant === "Link" ? (
              <Block
                className={`button_main_line ${_activeStyleVariant}`}
                tag={"div"}
              />
            ) : null}
            {!slotIsEmpty(icon) && !iconVisibility ? (
              <Block
                className={`button_main_icon_wrap ${_activeStyleVariant}`}
                tag={"div"}
              >
                {icon}
              </Block>
            ) : null}
            {iconVisibility && variant === "Link" ? (
              <Block
                className={`button_main_icon_wrap ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`button_main_icon ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <PhosphorIcon classProp={icon2} />
                </Block>
              </Block>
            ) : null}
            {iconVisibility && ["Square", "Secondary"].includes(variant) ? (
              <Block
                className={`button_main_icon_wrap ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`button_main_text_animation is-default ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`button_main_icon ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <PhosphorIcon classProp={icon2} />
                  </Block>
                </Block>
                <Block
                  className={`button_main_text_animation is-hover ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`button_main_icon ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <PhosphorIcon classProp={icon2} />
                  </Block>
                </Block>
              </Block>
            ) : null}
          </Block>
        </DOM>
      ) : null}
    </div>
  );
}
