/**
 * @generated
 * @file Block (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * Block
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Block({
  attributeName = "",
  attributeValue = "",
  classes = " ",
  content,
  style = "",
  tag = "div",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <DOM
          className={classes}
          // @ts-ignore - User-defined custom attribute(s)
          style={style}
          tag={tag}
          {...{
            [attributeName]: attributeValue,
          }}
        >
          {content}
        </DOM>
      ) : null}
    </div>
  );
}
