/**
 * @generated
 * @file ButtonWrapper (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";

/**
 * ButtonWrapper
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ButtonWrapper({
  content,
  marginBottom = 0,
  marginTop = -1,
  settingsAttributes = {},
  settingsStyle = "",
  settingsVisibility = false,
  variant = "Inherit",
}) {
  const _styleVariantMap = {
    Inherit: "",
    Left: "w-variant-51442304-f72a-1409-74f0-c40828d5fed5",
    Center: "w-variant-f167ee96-f512-86c8-3c9a-fe835778c474",
    Right: "w-variant-bc378dd1-1b9e-3b14-fed2-7fd0b5b78e75",
    Grow: "w-variant-2bec9480-c7a1-c240-7bd8-232ee446a098",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!slotIsEmpty(content) && settingsVisibility ? (
        <DOM className={`u-button-wrapper ${_activeStyleVariant}`} tag={"div"}>
          {content}
        </DOM>
      ) : null}
    </div>
  );
}
