/**
 * @generated
 * @file ContentWrapper (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * ContentWrapper
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ContentWrapper({
  content,
  settingsClasses = " ",
  settingsStyle = "",
  settingsVisibility = true,
  variant = "Left",
}) {
  const _styleVariantMap = {
    Inherit: "",
    Left: "w-variant-e85a4315-14bc-e5ef-0d3e-2c8c9ed7d2f1",
    Center: "w-variant-4f54624e-ceb1-0769-a238-365d5e220b70",
    Right: "w-variant-405b6754-709a-81de-bf32-f0102c0c7aa2",
    "Center Mobile": "w-variant-e98b91c1-a8bf-9b6d-a119-f398c9e3f46b",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`u-content-wrapper ${settingsClasses} ${_activeStyleVariant}`}
          // @ts-ignore - User-defined custom attribute(s)
          style={settingsStyle}
          tag={"div"}
        >
          {content}
        </DOM>
      ) : null}
    </div>
  );
}
