/**
 * @generated
 * @file FrameLayout (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { SpaceSwitcher } from "../variantSwitcher/SpaceSwitcher";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";

/**
 * FrameLayout
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FrameLayout({
  content,
  contentAttributes = {},
  contentBorderBottom = true,
  contentPaddingBottom = "Small",
  contentPaddingInline = true,
  contentPaddingTop = "Small",
  contentTheme = "Inherit",
  settingsAttributes = {},
  settingsId = "",
  settingsVisibility = true,
  theme = "Inherit",
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Column: "w-variant-ef513b06-9c05-c00a-fcf0-aa44be6dfe72",
    Columns: "w-variant-1060a7e5-bbbe-fff0-7188-7e3fbe264bcd",
    Blocks: "w-variant-4ec86e32-1a99-4250-2452-c5a0a15a891c",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <Block
          className={`frame_outer is-bordered ${_activeStyleVariant}`}
          data-border-bottom={null}
          data-frame-inner={variant === "Square" ? "False" : "True"}
          id={settingsId}
          tag={"div"}
          {...{
            [theme !== "Square" ? "class" : ""]:
              theme === "Light"
                ? "u-theme-light"
                : theme === "Grey"
                ? "u-theme-grey"
                : theme === "Brand"
                ? "u-theme-brand"
                : theme === "Accent1"
                ? "u-theme-accent1"
                : theme === "Accent2"
                ? "u-theme-accent2"
                : theme === "Dark"
                ? "u-theme-dark"
                : "",
          }}
          {...settingsAttributes}
        >
          <Block className={`frame_side ${_activeStyleVariant}`} tag={"div"}>
            <Block
              className={`frame_side_item ${_activeStyleVariant}`}
              tag={"div"}
            >
              {variant === "Blocks" ? (
                <Block
                  className={`frame_block is-accent1 ${_activeStyleVariant}`}
                  tag={"div"}
                />
              ) : null}
            </Block>
            {!["Square", "Column"].includes(variant) ? (
              <Block
                className={`frame_side_item ${_activeStyleVariant}`}
                tag={"div"}
              >
                {variant === "Blocks" ? (
                  <Block
                    className={`frame_block ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                ) : null}
              </Block>
            ) : null}
          </Block>
          {content}
          <Block
            className={`frame_side is-end ${_activeStyleVariant}`}
            tag={"div"}
          >
            {!["Square", "Column"].includes(variant) ? (
              <Block
                className={`frame_side_item ${_activeStyleVariant}`}
                tag={"div"}
              >
                {variant === "Blocks" ? (
                  <Block
                    className={`frame_block ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                ) : null}
              </Block>
            ) : null}
            <Block
              className={`frame_side_item ${_activeStyleVariant}`}
              tag={"div"}
            >
              {variant === "Blocks" ? (
                <Block
                  className={`frame_block is-accent1 ${_activeStyleVariant}`}
                  tag={"div"}
                />
              ) : null}
            </Block>
          </Block>
          <ThemeSwitcher theme={theme} />
          <ThemeSwitcher theme={contentTheme} />
          <SpaceSwitcher variant={contentPaddingTop} />
          <SpaceSwitcher variant={contentPaddingBottom} />
        </Block>
      ) : null}
    </div>
  );
}
