/**
 * @generated
 * @file FramedAside (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Section from "../webflow_modules/Layout/components/Section";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { conditional } from "../webflow_modules/Conditionals/helpers/conditional";
import { equals } from "../webflow_modules/Boolean/helpers/equals";
import { every } from "../webflow_modules/Boolean/helpers/every";
import { some } from "../webflow_modules/Boolean/helpers/some";
import { styleVariantIsAny } from "../webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * FramedAside
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FramedAside({
  frameLayout,
  settingsId = "",
  settingsSectionAttributes = {},
  settingsVisibility = false,
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  theme = "Inherit",
  transitionLeading = false,
  transitionTrailing = false,
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Sticky: "w-variant-ac31a957-349c-e654-a362-5fe86d0b6f95",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <Section
          className={`u-section u-padding-0 ${_activeStyleVariant}`}
          grid={{
            type: "section",
          }}
          id={settingsId}
          tag={"aside"}
          {...{
            [theme !== "Square" ? "class" : ""]:
              theme === "Light"
                ? "u-theme-light"
                : theme === "Grey"
                ? "u-theme-grey"
                : theme === "Brand"
                ? "u-theme-brand"
                : theme === "Accent1"
                ? "u-theme-accent1"
                : theme === "Accent2"
                ? "u-theme-accent2"
                : theme === "Dark"
                ? "u-theme-dark"
                : "",
          }}
          {...settingsSectionAttributes}
        >
          {conditional({
            rules: [
              {
                condition: every([
                  applyPredicate(spacerExplicit)(equals(true)),
                ]),
                output: spacerTop,
              },
              {
                condition: some([
                  applyPredicate(spacerTop)(equals(true)),
                  applyPredicate(theme)(styleVariantIsAny(["Brand", "Dark"])),
                ]),

                output: true,
              },
            ],

            fallback: false,
          }) ? (
            <Block
              className={`frame_wrap is-block ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`u-container is-framed ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`frame_outer ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
          ) : null}
          <Block className={`frame_wrap ${_activeStyleVariant}`} tag={"div"}>
            <Block
              className={`u-container is-framed ${_activeStyleVariant}`}
              tag={"div"}
            >
              {transitionLeading ? (
                <Block
                  className={`frame_outer is-transition2 ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner is-bordered ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_transition_inner ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                    </Block>
                  </Block>
                  <Block
                    className={`frame_side is-end ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              ) : null}
              {frameLayout}
              {transitionTrailing ? (
                <Block
                  className={`frame_outer is-transition2 ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner is-bordered ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_transition_inner ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                    </Block>
                  </Block>
                  <Block
                    className={`frame_side is-end ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              ) : null}
            </Block>
          </Block>
          {conditional({
            rules: [
              {
                condition: every([
                  applyPredicate(spacerExplicit)(equals(true)),
                ]),
                output: spacerBottom,
              },
              {
                condition: some([
                  applyPredicate(spacerBottom)(equals(true)),
                  applyPredicate(theme)(styleVariantIsAny(["Brand", "Dark"])),
                ]),

                output: true,
              },
            ],

            fallback: false,
          }) ? (
            <Block
              className={`frame_wrap is-block ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`u-container is-framed ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`frame_outer ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
          ) : null}
          <ThemeSwitcher theme={theme} />
        </Section>
      ) : null}
    </div>
  );
}
