/**
 * @generated
 * @file FramedSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Section from "../webflow_modules/Layout/components/Section";
import * as ix3 from "../webflow_modules/ix3-interactions";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { conditional } from "../webflow_modules/Conditionals/helpers/conditional";
import { equals } from "../webflow_modules/Boolean/helpers/equals";
import { every } from "../webflow_modules/Boolean/helpers/every";
import { some } from "../webflow_modules/Boolean/helpers/some";
import { styleVariantIsNotAny } from "../webflow_modules/Basic/helpers/styleVariantIsNotAny";

const ix3Data = JSON.parse(
  '{"interactions":[{"id":"i-ff9d2200","scope":{"type":"component","componentId":"820cc24f-6ae2-4165-dc48-6bc5abf33b64"},"triggers":[["wf:scroll",{"controlType":"scroll","scrollTriggerConfig":{"clamp":true,"start":"bottom bottom","end":"top top","scrub":1,"enter":"play","leave":"none","enterBack":"none","leaveBack":"none"}},["wf:class",["frame_outer.is-transition2"],{"relationship":"none","firstMatchOnly":false}]]],"timelineIds":["t-2491ea2c"],"conditionalPlayback":[{"type":"prefers-reduced-motion","behavior":"dont-animate","breakpoints":[]}],"deleted":false}],"timelines":[{"id":"t-2491ea2c","actions":[{"id":"ta-63a32074","targets":[["wf:class",["frame_transition_block"],{"relationship":"within","filterBy":["wf:trigger-only",""],"firstMatchOnly":false}]],"timing":{"duration":1,"position":0,"stagger":{"each":0.1,"from":"random"},"ease":0},"tt":0,"properties":{"wf:transform":{"opacity":[null,"0%"]}}}],"canvasDuration":1,"deleted":false}]}'
);

/**
 * FramedSection
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FramedSection({
  frameLayout,
  settingsId = "",
  settingsSectionAttributes = {},
  settingsVisibility = false,
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  theme = "Inherit",
  transitionLeading = false,
  transitionTrailing = false,
  variant = "Base",
}) {
  ix3.useIX3Interactions(ix3Data);

  const _styleVariantMap = {
    Base: "",
    Sticky: "w-variant-aea78978-f457-b8a3-f51f-707b433091c1",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  const _variantStateMap = {
    Base: "base",
    Sticky: "aea78978-f457-b8a3-f51f-707b433091c1",
  };

  const _activeVariantState = _variantStateMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <Section
          className={`u-section u-padding-0 ${_activeStyleVariant}`}
          data-wf-component-id={"820cc24f-6ae2-4165-dc48-6bc5abf33b64"}
          data-wf-variant-state={_activeVariantState}
          grid={{
            type: "section",
          }}
          tag={"section"}
          {...{
            [theme !== "Square" ? "class" : ""]:
              theme === "Light"
                ? "u-theme-light"
                : theme === "Grey"
                ? "u-theme-grey"
                : theme === "Brand"
                ? "u-theme-brand"
                : theme === "Accent1"
                ? "u-theme-accent1"
                : theme === "Accent2"
                ? "u-theme-accent2"
                : theme === "Dark"
                ? "u-theme-dark"
                : "",
          }}
          {...settingsSectionAttributes}
        >
          {conditional({
            rules: [
              {
                condition: every([
                  applyPredicate(transitionLeading)(equals(true)),
                ]),
                output: false,
              },
              {
                condition: every([
                  applyPredicate(spacerExplicit)(equals(true)),
                ]),
                output: spacerTop,
              },
              {
                condition: some([
                  applyPredicate(spacerTop)(equals(true)),
                  applyPredicate(theme)(
                    styleVariantIsNotAny(["Square", "Light"])
                  ),
                ]),

                output: true,
              },
            ],

            fallback: false,
          }) ? (
            <Block
              className={`frame_wrap is-block ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`u-container is-framed ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`frame_outer ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner is-bordered ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                  <Block
                    className={`frame_side is-end ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
          ) : null}
          <Block
            className={`frame_wrap ${_activeStyleVariant}`}
            id={settingsId}
            tag={"div"}
          >
            <Block
              className={`u-container is-framed ${_activeStyleVariant}`}
              tag={"div"}
            >
              {transitionLeading ? (
                <Block
                  className={`frame_outer is-transition2 ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner is-bordered ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_transition_inner ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                    </Block>
                  </Block>
                  <Block
                    className={`frame_side is-end ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              ) : null}
              {frameLayout}
              {transitionTrailing ? (
                <Block
                  className={`frame_outer is-transition2 ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner is-bordered ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_transition_inner ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                      <Block
                        className={`frame_transition_column is-desktop ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                        <Block
                          className={`frame_transition_block is-auto ${_activeStyleVariant}`}
                          tag={"div"}
                        />
                      </Block>
                    </Block>
                  </Block>
                  <Block
                    className={`frame_side is-end ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                      <Block
                        className={`frame_transition_block ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              ) : null}
            </Block>
          </Block>
          {conditional({
            rules: [
              {
                condition: every([
                  applyPredicate(transitionTrailing)(equals(true)),
                ]),
                output: false,
              },
              {
                condition: every([
                  applyPredicate(spacerExplicit)(equals(true)),
                ]),
                output: spacerBottom,
              },
              {
                condition: some([
                  applyPredicate(spacerBottom)(equals(true)),
                  applyPredicate(theme)(
                    styleVariantIsNotAny(["Square", "Light"])
                  ),
                ]),

                output: true,
              },
            ],

            fallback: false,
          }) ? (
            <Block
              className={`frame_wrap is-block ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`u-container is-framed ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`frame_outer ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`frame_side ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                  <Block
                    className={`frame_inner is-bordered ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                  <Block
                    className={`frame_side is-end ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                    <Block
                      className={`frame_side_item ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`frame_block is-placeholder ${_activeStyleVariant}`}
                        tag={"div"}
                      />
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
          ) : null}
          <ThemeSwitcher theme={theme} />
        </Section>
      ) : null}
    </div>
  );
}
