/**
 * @generated
 * @file Grid (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";

/**
 * Grid
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Grid({
  content,
  largeScreen = 2,
  mediumScreen = 1,
  minimumColumnSize = 12,
  settingsClasses = " ",
  settingsRole = false,
  settingsStyle = "",
  settingsVisibility = false,
  smallestScreen = 0,
  smallScreen = 0,
  variant = "Default",
}) {
  const _styleVariantMap = {
    Default: "",
    "Self Contained": "w-variant-b8204f2e-764d-b421-dc96-2c59d3054271",
    Autofit: "w-variant-d58244bf-290f-ebb3-3aa0-352d6fa8e84f",
    Autofill: "w-variant-129319ac-a2cd-9e88-2ebd-a33b4bb85fa5",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !slotIsEmpty(content) ? (
        <DOM
          className={`u-grid-wrapper ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(minimumColumnSize)}
          tag={"div"}
          {...{
            [settingsStyle !== "" ? "style" : ""]: settingsStyle,
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          {content}
        </DOM>
      ) : null}
    </div>
  );
}
