/**
 * @generated
 * @file Layout (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";

/**
 * Layout
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Layout({
  column1,
  column2,
  settingsClasses = "",
  settingsColumn1Classes = " ",
  settingsColumn2Classes = " ",
  settingsVisibility = false,
  variant = "Stack",
}) {
  const _styleVariantMap = {
    Stack: "",
    "Stack Centered": "w-variant-d69d5003-e9bc-b347-4e02-eb46976beb1c",
    "Auto Width": "w-variant-1b1d171f-31c6-739b-bff9-2d7efa9674c4",
    "Auto Width Reversed": "w-variant-204a3ebe-74bb-2187-4e31-75f83c71d79a",
    Columns: "w-variant-558793eb-2b07-490b-9842-2d7e6f6bf325",
    "Columns Reversed": "w-variant-1261a7e4-2c05-3b0b-2126-d399890906b8",
    "Sticky Left": "w-variant-81232c92-6578-ef9a-1e3e-35e3204ae0fd",
    Breakout: "w-variant-4fee4cc0-701f-2817-944f-2c0261b9c2f3",
    "Breakout Reversed": "w-variant-6bb5e515-55a9-1fc8-d29b-ff898d8b40f7",
    Full: "w-variant-58b19052-6f23-ab5e-5e89-54288af57e85",
    "Full Reversed": "w-variant-560ed4d9-9e8c-5c39-4619-fc154cdf9f19",
    Contain: "w-variant-31f8ed75-2c88-945a-a737-1b9b50b4494b",
    "Contain Reversed": "w-variant-329f6899-ba0f-e4db-0449-3c5b8ba4f388",
    Card: "w-variant-ebfcdcb1-ac53-1b15-fcb9-eaeda25808f5",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!slotIsEmpty(column1) && settingsVisibility ? (
        <DOM
          className={`u-layout-wrapper ${_activeStyleVariant}`}
          tag={"div"}
          {...{
            [settingsClasses !== "" ? "class" : ""]: settingsClasses,
          }}
        >
          <DOM className={`u-layout ${_activeStyleVariant}`} tag={"div"}>
            {column1}
            {column2}
          </DOM>
        </DOM>
      ) : null}
    </div>
  );
}
