/**
 * @generated
 * @file Section (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Section2 from "../webflow_modules/Layout/components/Section";
import { SpaceSwitcher } from "../variantSwitcher/SpaceSwitcher";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { conditional } from "../webflow_modules/Conditionals/helpers/conditional";
import { every } from "../webflow_modules/Boolean/helpers/every";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";
import { styleVariantIsAny } from "../webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * Section
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Section({
  background,
  container,
  height = true,
  paddingBottom = "Large",
  paddingTop = "Large",
  settingsContainerClasses = " ",
  settingsId = "",
  settingsSectionAttributes = {},
  settingsVisibility = false,
  theme = "Inherit",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {!slotIsEmpty(container) && settingsVisibility ? (
        <Section2
          className={`u-section ${conditional({
            rules: [
              {
                condition: every([
                  applyPredicate(theme)(styleVariantIsAny(["Light"])),
                ]),
                output: "u-theme-light",
              },
              {
                condition: every([
                  applyPredicate(theme)(styleVariantIsAny(["Grey"])),
                ]),
                output: "u-theme-dark",
              },
              {
                condition: every([
                  applyPredicate(theme)(styleVariantIsAny(["Brand"])),
                ]),
                output: "u-theme-brand",
              },
            ],

            fallback: "",
          })}`}
          grid={{
            type: "section",
          }}
          id={settingsId}
          tag={"section"}
          {...{
            [!height ? "class" : ""]: !height ? "u-min-height-screen" : "",
          }}
          {...settingsSectionAttributes}
        >
          {background}
          <SpaceSwitcher variant={paddingTop} />
          {container}
          <SpaceSwitcher variant={paddingBottom} />
          <ThemeSwitcher theme={theme} />
        </Section2>
      ) : null}
    </div>
  );
}
