/**
 * @generated
 * @file Clickable (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Link from "../webflow_modules/Basic/components/Link";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { linkIsNotSet } from "../webflow_modules/Basic/helpers/linkIsNotSet";
import { linkIsSet } from "../webflow_modules/Basic/helpers/linkIsSet";
import { listOfElementsToText } from "../webflow_modules/Basic/helpers/listOfElementsToText";

/**
 * Clickable
 *
 * This makes its whole parent clickable & can be a link tag or a button tag if the url field is left empty. It has hidden text that is readable by screen readers and has a z-index: 0 only in designer view to keep any relative content clickable.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Clickable({
  attributes = {},
  buttonType = false,

  link = {
    href: "#",
  },

  screenReaderText = "",
  variant = "Focus Ring Outside",
  visibility = true,
}) {
  const _styleVariantMap = {
    "Focus Ring Outside": "",
    "Focus Ring Inside": "w-variant-b793638f-e9bb-2cea-c2d9-27bf5a1f754a",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <DOM
          className={`clickable_wrap u-cover-absolute ${_activeStyleVariant}`}
          tag={"div"}
        >
          {applyPredicate(link)(linkIsSet) ? (
            <Link
              aria-label={listOfElementsToText(screenReaderText)}
              block={"inline"}
              button={false}
              className={`clickable_link ${_activeStyleVariant}`}
              options={link}
              {...attributes}
            />
          ) : null}
          {applyPredicate(link)(linkIsNotSet) ? (
            <DOM
              className={`clickable_btn ${_activeStyleVariant}`}
              tag={"button"}
            />
          ) : null}
        </DOM>
      ) : null}
    </div>
  );
}
