/**
 * @generated
 * @file StarterJs (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * StarterJs
 *
 * Unlink before use. Include as last child within component. Replace 'yourFunctionName' in the embed with a name that is specific to your component.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function StarterJs({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <HtmlEmbed
        className={"u-embed-js"}
        content={
          '<script>\n(function() {\n  const component = document.currentScript.parentElement.parentElement;\n  document.addEventListener("DOMContentLoaded", function () {\n    // run script here\n  });\n})();\n</script>'
        }
      />
    </div>
  );
}
