/**
 * @generated
 * @file StarterCss (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * StarterCss
 *
 * Unlink before use. Include as first child within component.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function StarterCss({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <HtmlEmbed className={"u-embed-css"} content={"<style>\n\n</style>"} />
    </div>
  );
}
