/**
 * @generated
 * @file NavDropdownListItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Link from "./webflow_modules/Basic/components/Link";
import { toText } from "./webflow_modules/ListOfElements/helpers/toText";

/**
 * NavDropdownListItem
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function NavDropdownListItem({
  link = {
    href: "#",
    preload: "prefetch",
  },

  sub = "",
  title = "Title",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"nav_dropdown_item"}
        // @ts-ignore - User-defined custom attribute(s)
        role={"listitem"}
        tag={"div"}
      >
        <Link
          block={"inline"}
          button={false}
          className={"nav_dropdown_link"}
          data-trigger={"hover-other"}
          options={link}
        >
          <Block className={"nav_dropdown_text"} tag={"div"}>
            {title}
          </Block>
          {!!toText(sub) ? (
            <Block
              className={"nav_dropdown_text_sub u-text-style-xsmall u-faded"}
              tag={"div"}
            >
              {sub}
            </Block>
          ) : null}
        </Link>
      </Block>
    </div>
  );
}
