/**
 * @generated
 * @file AnchorLinksSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { AnchorLinks } from "../navigation/AnchorLinks";
import { FramedSection } from "../wrapper/FramedSection";
import { FrameLayout } from "../wrapper/FrameLayout";

/**
 * AnchorLinksSection
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function AnchorLinksSection({ anchorLink }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"u-display-contents"}
        data-anchor-links={"section"}
        tag={"div"}
      >
        <FramedSection
          frameLayout={
            <FrameLayout
              content={<AnchorLinks anchorLink={anchorLink} />}
              contentPaddingBottom={"None"}
              contentPaddingTop={"None"}
              variant={"Column"}
            />
          }
          spacerBottom={false}
          variant={"Sticky"}
        />
      </Block>
    </div>
  );
}
