/**
 * @generated
 * @file CustomersSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { Customers } from "../cms/Customers";
import { FramedSection } from "../wrapper/FramedSection";
import { FrameLayout } from "../wrapper/FrameLayout";
import { Layout } from "../wrapper/Layout";
import { PopoverTarget } from "../miscellaneous/PopoverTarget";
import { PopoverTrigger } from "../miscellaneous/PopoverTrigger";
import { Span } from "../typography/Span";
import { TextWPopover } from "../typography/TextWPopover";
import { TypographyEyebrow } from "../typography/TypographyEyebrow";

/**
 * CustomersSection
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported props: `Customers/Filters`, `Customers/Sort`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CustomersSection({
  logosHideFromIndex = 10,
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  theme = "Inherit",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block tag={"div"}>
        <FramedSection
          frameLayout={
            <>
              <FrameLayout
                content={
                  <Layout
                    column1={
                      <>
                        <TypographyEyebrow
                          text={<Heading tag={"h2"}>{"Customers"}</Heading>}
                        />
                        <TextWPopover
                          maxWidth={36}
                          popoverTarget={
                            <PopoverTarget
                              id={"7x-faster-popover"}
                              text={
                                "Source: 65% of UK businesses are paid late (source: 2025 FreeAgent survey of 200k+ businesses) vs 9% for Adfin (source: all Adfin customers, for all time)."
                              }
                            />
                          }
                          tag={"h3"}
                          text={
                            <>
                              <Span
                                text={
                                  "2,500+ of the most ambitious businesses getting paid"
                                }
                              />
                              <PopoverTrigger
                                idFor={"7x-faster-popover"}
                                text={"7x faster"}
                              />
                              <Span text={"than the average UK business"} />
                            </>
                          }
                          variant={"Text Large"}
                        />
                      </>
                    }
                    column2={
                      <ButtonWrapper
                        content={
                          <ButtonMain
                            link={{
                              href: "/customer-stories",
                              preload: "prefetch",
                            }}
                            text={"Learn more"}
                          />
                        }
                      />
                    }
                    variant={"Auto Width"}
                  />
                }
                contentPaddingTop={"Large"}
              />
              <FrameLayout
                content={
                  <Customers
                    customerLogosFilters={customersFilters}
                    customerLogosLimit={logosHideFromIndex}
                    customerLogosSort={customersSort}
                  />
                }
                contentPaddingBottom={"None"}
                contentPaddingTop={"None"}
                contentTheme={"Grey"}
                variant={"Column"}
              />
            </>
          }
          settingsId={"customers"}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
