/**
 * @generated
 * @file FeedbackSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";
import { CardPrimary } from "../card/CardPrimary";
import { ContentWrapper } from "../wrapper/ContentWrapper";
import { FramedSection } from "../wrapper/FramedSection";
import { FrameLayout } from "../wrapper/FrameLayout";
import { Slider } from "../interactive/Slider";
import { SliderControls } from "../interactive/SliderControls";
import { TypographyEyebrow } from "../typography/TypographyEyebrow";
import { TypographyHeading } from "../typography/TypographyHeading";
import { VisualImage } from "../visual/VisualImage";
import { VisualVideo } from "../visual/VisualVideo";

/**
 * FeedbackSection
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported props: `Filters`, `Sort`
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function FeedbackSection({
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  theme = "Inherit",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedSection
          frameLayout={
            <>
              <FrameLayout
                content={
                  <ContentWrapper
                    content={
                      <>
                        <TypographyEyebrow
                          text={
                            <Heading tag={"h2"}>{"CUSTOMERSTORIES"}</Heading>
                          }
                        />
                        <TypographyHeading
                          text={
                            <Heading tag={"h2"}>
                              {"Don't take our word for it"}
                            </Heading>
                          }
                          variant={"H4"}
                        />
                      </>
                    }
                  />
                }
                contentPaddingTop={"Large"}
              />
              <FrameLayout
                content={
                  <Slider
                    content={
                      <>
                        <NotSupported _atom={"Collection List"} />
                        <CardPrimary
                          cardType={"Video"}
                          visual={<VisualImage variant={"Tall 2 / 3"} />}
                        />
                        <CardPrimary
                          cardType={"Video"}
                          visual={<VisualImage variant={"Tall 2 / 3"} />}
                        />
                        <CardPrimary
                          cardType={"Video"}
                          visual={<VisualImage variant={"Tall 2 / 3"} />}
                        />
                        <CardPrimary
                          cardType={"Video"}
                          visual={<VisualImage variant={"Tall 2 / 3"} />}
                        />
                      </>
                    }
                    largeScreen={2.25}
                    listClasses={"u-gap-0"}
                    settingsCenteredSlides={false}
                    settingsLoop={false}
                    sliderControls={<SliderControls variant={"Progress"} />}
                  />
                }
                contentTheme={"Inherit"}
              />
            </>
          }
          settingsId={"feedback"}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
