/**
 * @generated
 * @file GetStartedCta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { CtaCard } from "../card/CtaCard";
import { FramedAside } from "../wrapper/FramedAside";
import { FrameLayout } from "../wrapper/FrameLayout";

/**
 * GetStartedCta
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function GetStartedCta({
  image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a69cb8ca361f85b63b37ec5_placeholder.svg",
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  sub = "",
  theme = "Inherit",
  title = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedAside
          frameLayout={
            <FrameLayout
              content={
                <CtaCard
                  actionLeft={
                    <ButtonWrapper
                      content={
                        <>
                          <ButtonMain text={"Sign up"} />
                          <ButtonMain
                            text={"Book a demo"}
                            variant={"Secondary"}
                          />
                        </>
                      }
                    />
                  }
                  actionNew={
                    <>
                      <ButtonMain
                        link={{
                          href: "https://console.adfin.com",
                        }}
                        text={"Sign up"}
                      />
                      <ButtonMain text={"Book a demo"} variant={"Secondary"} />
                    </>
                  }
                  ctaMain1Variant={"Stacked"}
                  subText={sub}
                  subVisibility={true}
                  theme={"Accent2"}
                  titleText={title}
                  visualImage={image}
                />
              }
              contentPaddingBottom={"Large"}
              contentPaddingTop={"Large"}
            />
          }
          settingsId={"get-started"}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
