/**
 * @generated
 * @file HowItWorksSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import { CardsList } from "../card/CardsList";
import { FramedSection } from "../wrapper/FramedSection";
import { FrameLayout } from "../wrapper/FrameLayout";
import { StackedCard } from "../card/StackedCard";
import { TypographyEyebrow } from "../typography/TypographyEyebrow";
import { TypographyHeading } from "../typography/TypographyHeading";

/**
 * HowItWorksSection
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function HowItWorksSection({
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  theme = "Inherit",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedSection
          frameLayout={
            <>
              <FrameLayout
                content={
                  <>
                    <TypographyEyebrow
                      text={<Paragraph>{"How it works"}</Paragraph>}
                    />
                    <TypographyHeading
                      maxWidth={10}
                      text={
                        <Heading tag={"h3"}>
                          {"Just get paid by direct debit"}
                        </Heading>
                      }
                      variant={"H3"}
                    />
                  </>
                }
                contentBorderBottom={true}
                contentPaddingBottom={"None"}
                contentPaddingTop={"Large"}
              />
              <FrameLayout
                content={
                  <CardsList
                    card={
                      <>
                        <StackedCard
                          headingText={
                            <Heading tag={"h4"}>{"Recurring payments"}</Heading>
                          }
                          paragraphText={
                            <Paragraph>
                              {
                                "Automatically collect payments by direct debit or card. If a direct debit fails, we retry free and can fall back to a card on file or send a payment link."
                              }
                            </Paragraph>
                          }
                          variant={"Fixed Visual"}
                          visualImageImage={
                            "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a9020b47e4ca88803cb0a63_b9553bb2d19d83a99154e7d60ec1d37f_recurring-payments.svg"
                          }
                        />
                        <StackedCard
                          headingText={
                            <Heading tag={"h4"}>{"One-off payments"}</Heading>
                          }
                          paragraphText={
                            <Paragraph>
                              {
                                "Send a payment link by WhatsApp, SMS or email. Customers pay in a tap: card, Apple Pay, Google Pay, or straight from their banking app."
                              }
                            </Paragraph>
                          }
                          v0EmbedSourceUrl={
                            "https://new-payment-hero-animation.vercel.app"
                          }
                          variant={"Fixed Visual"}
                          visualImageImage={
                            "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a9020b432352d2aba1fd4bc_late-fees.svg"
                          }
                          visualImageVariant={"Wide 16 / 9"}
                          visualImageVisibility={true}
                        />
                        <StackedCard
                          headingText={
                            <Heading tag={"h4"}>
                              {"Instant reconciliation"}
                            </Heading>
                          }
                          paragraphText={
                            <Paragraph>
                              {
                                "We bill our fees separately, so what lands in your bank matches the invoice exactly. Invoices are marked as paid in Xero or QuickBooks automatically."
                              }
                            </Paragraph>
                          }
                          variant={"Fixed Visual"}
                          visualImageImage={
                            "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a9020b4d12103a82d647619_late-reconciliation.svg"
                          }
                        />
                      </>
                    }
                  />
                }
                contentPaddingBottom={"None"}
                contentPaddingTop={"None"}
                variant={"Column"}
              />
            </>
          }
          settingsId={"features"}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
