/**
 * @generated
 * @file NewsletterCta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { CtaCard } from "../card/CtaCard";
import { EmailForm } from "../form/EmailForm";
import { FramedAside } from "../wrapper/FramedAside";
import { FrameLayout } from "../wrapper/FrameLayout";

/**
 * NewsletterCta
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function NewsletterCta({
  image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a69cb8ca361f85b63b37ec5_placeholder.svg",
  sectionTheme = "Inherit",
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  sub = "",
  theme = "Accent2",
  title = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedAside
          frameLayout={
            <FrameLayout
              content={
                <CtaCard
                  actionLeft={
                    <ButtonWrapper
                      content={
                        <>
                          <ButtonMain text={"Sign up"} />
                          <ButtonMain
                            text={"Book a demo"}
                            variant={"Secondary"}
                          />
                        </>
                      }
                    />
                  }
                  actionNew={<EmailForm form={false} theme={"Light"} />}
                  ctaMain1Variant={"Stacked"}
                  subText={sub}
                  subVisibility={true}
                  theme={theme}
                  titleText={title}
                  visualImage={image}
                />
              }
              contentPaddingBottom={"Large"}
              contentPaddingTop={"Large"}
              contentTheme={"Inherit"}
            />
          }
          settingsId={"get-started"}
          settingsVisibility={true}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={sectionTheme}
        />
      </Block>
    </div>
  );
}
