/**
 * @generated
 * @file PricingCalculatorCta (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { CtaCard } from "../card/CtaCard";
import { FramedAside } from "../wrapper/FramedAside";
import { FrameLayout } from "../wrapper/FrameLayout";

/**
 * PricingCalculatorCta
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function PricingCalculatorCta({
  image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a95ea1a27e10576fec94963_f2723d2b305ee19268ca20ecac63355f_Frame%202087328723.svg",
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  sub = "",
  theme = "Inherit",
  title = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedAside
          frameLayout={
            <FrameLayout
              content={
                <CtaCard
                  actionRight={
                    <ButtonWrapper
                      content={
                        <>
                          <ButtonMain text={"See our pricing"} />
                          <ButtonMain
                            text={"Try the pricing calculator"}
                            variant={"Secondary"}
                          />
                        </>
                      }
                      variant={"Right"}
                    />
                  }
                  subText={sub}
                  theme={"Grey"}
                  titleText={title}
                  titleVariant={"H3"}
                  visualImage={image}
                />
              }
              contentPaddingBottom={"Large"}
              contentPaddingTop={"Large"}
            />
          }
          settingsId={""}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
