/**
 * @generated
 * @file StatsSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { BarCard } from "../card/BarCard";
import { CardsList } from "../card/CardsList";
import { FramedSection } from "../wrapper/FramedSection";
import { FrameLayout } from "../wrapper/FrameLayout";
import { TypographyEyebrow } from "../typography/TypographyEyebrow";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";

/**
 * StatsSection
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function StatsSection({
  card1Stat = "7x",
  card1Sub = "Adfin customers are paid 7x faster than the UK average",
  card1Visibility = true,
  card2Stat = "£30k",
  card2Sub = "Saved in working capital and credit control costs",
  card2Visibility = true,
  card3Stat = "80+",
  card3Sub = "Hours saved monthly vs manual credit control",
  card3Visibility = true,
  eyebrow = "",
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  sub = "",
  subVisibility = false,
  theme = "Inherit",
  title = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedSection
          frameLayout={
            <>
              <FrameLayout
                content={
                  <>
                    <TypographyEyebrow text={eyebrow} />
                    <TypographyHeading
                      maxWidth={10}
                      text={title}
                      variant={"H3"}
                    />
                    <TypographyParagraph
                      settingsVisibility={subVisibility}
                      text={sub}
                    />
                  </>
                }
                contentPaddingBottom={"None"}
                contentPaddingTop={"Large"}
              />
              <FrameLayout
                content={
                  <CardsList
                    card={
                      <>
                        <BarCard
                          stat={card1Stat}
                          sub={card1Sub}
                          visibility={card1Visibility}
                        />
                        <BarCard
                          stat={card2Stat}
                          sub={card2Sub}
                          visibility={card2Visibility}
                        />
                        <BarCard
                          stat={card3Stat}
                          sub={card3Sub}
                          visibility={card3Visibility}
                        />
                      </>
                    }
                    settingsMinWidth={18}
                  />
                }
                contentPaddingBottom={"None"}
                contentPaddingTop={"None"}
                variant={"Column"}
              />
            </>
          }
          settingsId={"the-stats"}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
