/**
 * @generated
 * @file SwitchSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { ContentWrapper } from "../wrapper/ContentWrapper";
import { FramedSection } from "../wrapper/FramedSection";
import { FrameLayout } from "../wrapper/FrameLayout";
import { Layout } from "../wrapper/Layout";
import { ProgressCard } from "../card/ProgressCard";
import { ProgressTabs } from "../interactive/ProgressTabs";
import { TypographyEyebrow } from "../typography/TypographyEyebrow";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";

/**
 * SwitchSection
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function SwitchSection({
  card1Sub = "",
  card1Title = "",
  card2Sub = "",
  card2Title = "",
  card3Sub = "",
  card3Title = "",
  eyebrow = "",
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  sub = "",
  subVisibility = true,
  theme = "Grey",
  title = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedSection
          frameLayout={
            <>
              <FrameLayout
                content={
                  <Layout
                    column1={
                      <ContentWrapper
                        content={
                          <>
                            <TypographyEyebrow text={eyebrow} />
                            <TypographyHeading text={title} variant={"H3"} />
                            <TypographyParagraph
                              maxWidth={44}
                              settingsClasses={"u-faded"}
                              settingsVisibility={subVisibility}
                              text={sub}
                            />
                          </>
                        }
                      />
                    }
                    column2={
                      <ButtonWrapper
                        content={<ButtonMain text={"Learn more"} />}
                      />
                    }
                    variant={"Auto Width"}
                  />
                }
                contentPaddingTop={"Large"}
              />
              <FrameLayout
                content={
                  <ProgressTabs
                    card={
                      <>
                        <ProgressCard
                          content={
                            <>
                              <TypographyParagraph
                                text={<Paragraph>{"01"}</Paragraph>}
                                variant={"H5"}
                              />
                              <TypographyHeading
                                text={card1Title}
                                variant={"Text Large"}
                              />
                              <TypographyParagraph
                                settingsClasses={"u-faded"}
                                text={card1Sub}
                                variant={"Text Small"}
                              />
                            </>
                          }
                        />
                        <ProgressCard
                          content={
                            <>
                              <TypographyParagraph
                                text={<Paragraph>{"02"}</Paragraph>}
                                variant={"H5"}
                              />
                              <TypographyHeading
                                text={card2Title}
                                variant={"Text Large"}
                              />
                              <TypographyParagraph
                                settingsClasses={"u-faded"}
                                text={card2Sub}
                                variant={"Text Small"}
                              />
                            </>
                          }
                        />
                        <ProgressCard
                          content={
                            <>
                              <TypographyParagraph
                                text={<Paragraph>{"03"}</Paragraph>}
                                variant={"H5"}
                              />
                              <TypographyHeading
                                text={card3Title}
                                variant={"Text Large"}
                              />
                              <TypographyParagraph
                                settingsClasses={"u-faded"}
                                text={card3Sub}
                                variant={"Text Small"}
                              />
                            </>
                          }
                        />
                      </>
                    }
                    theme={"Light"}
                  />
                }
                contentAttributes={{
                  class: "u-padding-1",
                }}
                contentPaddingBottom={"None"}
                contentPaddingTop={"None"}
                variant={"Column"}
              />
            </>
          }
          settingsId={"switch"}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
