/**
 * @generated
 * @file WhyAdfinSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonMain } from "../button/ButtonMain";
import { CardsList } from "../card/CardsList";
import { FramedSection } from "../wrapper/FramedSection";
import { FrameLayout } from "../wrapper/FrameLayout";
import { StackedCard } from "../card/StackedCard";
import { TypographyEyebrow } from "../typography/TypographyEyebrow";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";

/**
 * WhyAdfinSection
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function WhyAdfinSection({
  card1Image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a95f0a2c522de30e4eb7de6_f465b65d0fead1965d63dac4375aa4ea_Payment%20methods.svg",
  card1ImageVisibility = true,
  card1Sub = "",
  card1Title = "",
  card1V0SourceUrl = "",
  card1V0Title = "UI animation",
  card1Visibility = true,
  card2Image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a95f0d96f1ab9bb7e6988c0_99dc07ae5332dcf31037ba5590db8f7f_Credit%20control%20widget.svg",
  card2ImageVisibility = false,
  card2Sub = "",
  card2Title = "",
  card2V0SourceUrl = "https://credit-control-widget.vercel.app",
  card2V0Title = "UI animation",
  card2Visibility = true,
  card3Image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a901e8dd6a587557d12999f_8bbb5fdeae4029ef23bd6da3b80bc37c_connect-systems.svg",
  card3ImageVisibility = false,
  card3Sub = "",
  card3Title = "",
  card3V0SourceUrl = "https://new-integrations-animation.vercel.app",
  card3V0Title = "UI animation",
  card3Visibility = true,
  card4Image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a901e8dd6a587557d12999f_8bbb5fdeae4029ef23bd6da3b80bc37c_connect-systems.svg",
  card4ImageVisibility = false,
  card4Sub = "",
  card4Title = "",
  card4V0SourceUrl = "https://new-integrations-animation.vercel.app",
  card4V0Title = "UI animation",
  card4Visibility = true,
  content = true,
  eyebrow = "",
  spacerBottom = true,
  spacerExplicit = false,
  spacerTop = false,
  stackedCardHover,
  sub = "",
  subVisibility = false,
  theme = "Inherit",
  title = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"u-display-contents"} tag={"div"}>
        <FramedSection
          frameLayout={
            <>
              <FrameLayout
                content={
                  <>
                    <TypographyEyebrow text={eyebrow} />
                    <TypographyHeading
                      maxWidth={10}
                      text={title}
                      variant={"H3"}
                    />
                    <TypographyParagraph
                      settingsVisibility={subVisibility}
                      text={sub}
                    />
                  </>
                }
                contentPaddingBottom={"None"}
                contentPaddingTop={"Large"}
              />
              <FrameLayout
                content={
                  <>
                    <CardsList
                      card={
                        <>
                          <StackedCard
                            button={
                              <ButtonMain
                                link={{
                                  href: "/accept-payments",
                                }}
                                text={"Learn more about Payments"}
                                variant={"Link"}
                              />
                            }
                            cardType={"Hover"}
                            headingText={card1Title}
                            paragraphText={card1Sub}
                            v0EmbedSourceUrl={card1V0SourceUrl}
                            v0EmbedTitleAccessibility={card1V0Title}
                            visibility={card1Visibility}
                            visualImageImage={card1Image}
                            visualImageVariant={"Wide 16 / 9"}
                            visualImageVisibility={card1ImageVisibility}
                          />
                          <StackedCard
                            button={
                              <ButtonMain
                                link={{
                                  href: "/credit-control",
                                }}
                                text={"Learn more about Credit Control"}
                                variant={"Link"}
                              />
                            }
                            cardType={"Hover"}
                            headingText={card2Title}
                            paragraphText={card2Sub}
                            v0EmbedSourceUrl={card2V0SourceUrl}
                            v0EmbedTitleAccessibility={card2V0Title}
                            visibility={card2Visibility}
                            visualImageImage={card2Image}
                            visualImageVisibility={card2ImageVisibility}
                          />
                          <StackedCard
                            cardType={"Hover"}
                            headingText={card3Title}
                            paragraphText={card3Sub}
                            paragraphVisibility={true}
                            v0EmbedSourceUrl={card3V0SourceUrl}
                            v0EmbedTitleAccessibility={card3V0Title}
                            visibility={card3Visibility}
                            visualImageImage={card3Image}
                            visualImageVisibility={card3ImageVisibility}
                          />
                          <StackedCard
                            cardType={"Hover"}
                            headingText={card4Title}
                            paragraphText={card4Sub}
                            v0EmbedSourceUrl={card4V0SourceUrl}
                            v0EmbedTitleAccessibility={card4V0Title}
                            visibility={card4Visibility}
                            visualImageImage={card4Image}
                            visualImageVisibility={card4ImageVisibility}
                          />
                        </>
                      }
                      settingsVisibility={content ? true : false}
                    />
                    <CardsList
                      card={stackedCardHover}
                      settingsVisibility={!content ? true : false}
                    />
                  </>
                }
                contentPaddingBottom={"None"}
                contentPaddingTop={"None"}
                variant={"Column"}
              />
            </>
          }
          settingsId={"just-get-paid"}
          spacerBottom={spacerBottom}
          spacerExplicit={spacerExplicit}
          spacerTop={spacerTop}
          theme={theme}
        />
      </Block>
    </div>
  );
}
