/**
 * @generated
 * @file BorderDivider (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * BorderDivider
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function BorderDivider({ marginBlock = 0, visibility = true }) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          className={"u-divider"}
          tag={"div"}
          {...{
            [marginBlock !== 0 ? "class" : ""]:
              marginBlock === 1
                ? "u-margin-top-1 u-margin-bottom-1"
                : marginBlock === 2
                ? "u-margin-top-2 u-margin-bottom-2"
                : marginBlock === 3
                ? "u-margin-top-3 u-margin-bottom-3"
                : marginBlock === 4
                ? "u-margin-top-4 u-margin-bottom-4"
                : marginBlock === 5
                ? "u-margin-top-5 u-margin-bottom-5"
                : marginBlock === 6
                ? "u-margin-top-6 u-margin-bottom-6"
                : marginBlock === 7
                ? "u-margin-top-7 u-margin-bottom-7"
                : marginBlock === 8
                ? "u-margin-top-8 u-margin-bottom-8"
                : "",
          }}
        />
      ) : null}
    </div>
  );
}
