/**
 * @generated
 * @file VerticalLine (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * VerticalLine
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function VerticalLine({ variant = "Base" }) {
  const _styleVariantMap = {
    Base: "",
    "Hide Medium": "w-variant-46bd0d5d-4a4a-7fc7-fd93-820f5c034ee8",
    "Hide Small": "w-variant-93515d30-33a5-411f-218f-55d46c692202",
    "Hide xSmall": "w-variant-e6d25dba-71d2-955c-7f8c-f09f0fdbc176",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`vertical-lines_line ${_activeStyleVariant}`}
        tag={"div"}
      />
    </div>
  );
}
