/**
 * @generated
 * @file VerticalLines (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { VerticalLine } from "./VerticalLine";

/**
 * VerticalLines
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function VerticalLines({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"vertical-lines_component"} tag={"div"}>
        <VerticalLine />
        <Block className={"vertical-lines_oval"} tag={"div"} />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Medium"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide Small"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine variant={"Hide xSmall"} />
        <VerticalLine />
      </Block>
    </div>
  );
}
