/**
 * @generated
 * @file BarCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";

/**
 * BarCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function BarCard({
  stat = "Stat",
  sub = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={"cards-wrap_item"} tag={"div"}>
          <Block
            className={"hover-card_wrap"}
            data-trigger={"hover focus"}
            tag={"div"}
          >
            <Block className={"hover-card_main"} tag={"div"}>
              <Block className={"u-text-style-h1"} tag={"div"}>
                {stat}
              </Block>
              <Paragraph className={"u-text-style-small"}>{sub}</Paragraph>
            </Block>
            <Block className={"hover-card_bar"} tag={"div"} />
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
