/**
 * @generated
 * @file CardsList (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * CardsList
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CardsList({
  card,
  settingsAttributes = {},
  settingsMinWidth = 18,
  settingsVisibility = true,
  theme = "Inherit",
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Gap: "w-variant-d8999fc1-5bec-96d8-a285-36e8e3f067ee",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <Block
          className={`cards-wrap_component ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(settingsMinWidth)}
          tag={"div"}
          {...{
            [theme !== "Square" ? "class" : ""]:
              theme === "Light"
                ? "u-theme-light"
                : theme === "Grey"
                ? "u-theme-grey"
                : theme === "Brand"
                ? "u-theme-brand"
                : theme === "Accent1"
                ? "u-theme-accent1"
                : theme === "Accent2"
                ? "u-theme-accent2"
                : theme === "Dark"
                ? "u-theme-dark"
                : "",
          }}
          {...settingsAttributes}
        >
          {card}
          <ThemeSwitcher theme={theme} />
        </Block>
      ) : null}
    </div>
  );
}
