/**
 * @generated
 * @file CardPrimary (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { Clickable } from "../utility/Clickable";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { conditional } from "../webflow_modules/Conditionals/helpers/conditional";
import { equals } from "../webflow_modules/Boolean/helpers/equals";
import { every } from "../webflow_modules/Boolean/helpers/every";
import { linkIsSet } from "../webflow_modules/Basic/helpers/linkIsSet";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * CardPrimary
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CardPrimary({
  background = true,
  border = false,
  cardType = "Default",
  content,

  link = {
    href: "#",
  },

  screenReaderText = "Learn More",
  settingsCardAttributes = {},
  settingsClickableAttributes = {},
  settingsRole = true,
  settingsTheme = "Inherit",
  settingsVisibility = false,
  settingsWrapperClasses = "",
  settingsWrapperStyle = "",
  visual,
  visualVisibility = true,
}) {
  const _styleVariantMap = {
    Default: "",
    Cover: "w-variant-51efa20c-c7be-48fe-973a-11367f19d622",
    Stacked: "w-variant-da648fa9-bbba-c8cb-e549-1d22cb8af97b",
    Hover: "w-variant-442048ad-bb2d-d072-5358-08c5e99608ed",
    Video: "w-variant-93392bc5-8e82-8f89-91f7-9d452bcd3105",
    Logo: "w-variant-6cd3c3c4-96e0-c1c3-817e-00b243c0a3fe",
    Stat: "w-variant-dbc19c7c-4e4e-8c78-a0a3-bfc6f31b5383",
    Horizontal: "w-variant-2255327f-31b9-4a63-27fd-3c68896f561d",
    Event: "w-variant-9c9f3d96-6322-0875-68cc-bee5469cc219",
    "Blog Vertical": "w-variant-777432d1-c86a-31c5-e958-223de20a538f",
    Quote: "w-variant-0e5a4746-9986-ace3-c550-b84e4068c771",
    "Full Visual": "w-variant-9227cd42-fc5c-fd7f-2d29-e79cf11224fc",
  };

  const _activeStyleVariant = _styleVariantMap[cardType];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`card_primary_wrap ${_activeStyleVariant}`}
          tag={"div"}
          {...{
            [settingsWrapperClasses !== "" ? "class" : ""]:
              settingsWrapperClasses,
            [settingsWrapperStyle !== "" ? "style" : ""]: settingsWrapperStyle,
            [settingsRole ? "" : "role"]: settingsRole ? "" : "listitem",
          }}
        >
          <Block
            className={`card_primary_group ${_activeStyleVariant}`}
            data-trigger={"hover-if-clickable focus"}
            tag={"div"}
          >
            <Block
              className={`card_primary_element ${conditional({
                rules: [
                  {
                    condition: every([
                      applyPredicate(background)(equals(true)),
                    ]),
                    output: "u-background-1",
                  },
                  {
                    condition: every([
                      applyPredicate(background)(equals(false)),
                    ]),
                    output: "u-background-2",
                  },
                ],

                fallback: "",
              })} ${_activeStyleVariant}`}
              tag={"div"}
              {...{
                [cardType === "Hover" ? "data-trigger" : ""]:
                  cardType === "Hover" ? "hover focus" : "",
                [border ? "class" : ""]: border ? "u-border" : "",
              }}
              {...settingsCardAttributes}
            >
              {visual}
              {content}
            </Block>
            <Clickable
              link={link}
              screenReaderText={screenReaderText}
              visibility={
                !!toText(screenReaderText) && applyPredicate(link)(linkIsSet)
                  ? true
                  : false
              }
            />
          </Block>
          <ThemeSwitcher theme={settingsTheme} />
        </DOM>
      ) : null}
    </div>
  );
}
