/**
 * @generated
 * @file CardCheckList (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { BorderDivider } from "../decorative/BorderDivider";
import { CheckList } from "../miscellaneous/CheckList";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";

/**
 * CardCheckList
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CardCheckList({
  checkListItem,
  headingText = "",
  phosphorIconClass = "ph-user",
  subText = "",
  subVisibility = true,
  theme = "Inherit",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          className={"check-list_card_component"}
          tag={"div"}
          {...{
            [theme !== "Square" ? "class" : ""]:
              theme === "Light"
                ? "u-theme-light"
                : theme === "Grey"
                ? "u-theme-grey"
                : theme === "Brand"
                ? "u-theme-brand"
                : theme === "Accent1"
                ? "u-theme-accent1"
                : theme === "Accent2"
                ? "u-theme-accent2"
                : theme === "Dark"
                ? "u-theme-dark"
                : "",
          }}
        >
          <Block className={"check-list_card_icon"} tag={"div"}>
            <PhosphorIcon classProp={phosphorIconClass} variant={"Huge"} />
          </Block>
          <TypographyHeading
            settingsClasses={"u-font-serif"}
            text={headingText}
            variant={"H3"}
          />
          <TypographyParagraph
            marginBottom={0}
            settingsVisibility={subVisibility}
            text={subText}
            variant={"Text Small"}
          />
          <BorderDivider marginBlock={5} />
          <CheckList checkListItem={checkListItem} />
          <ThemeSwitcher theme={theme} />
        </Block>
      ) : null}
    </div>
  );
}
