/**
 * @generated
 * @file CtaCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Image from "../webflow_modules/Basic/components/Image";
import { CtaMain } from "./CtaMain";
import { Layout } from "../wrapper/Layout";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";

/**
 * CtaCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CtaCard({
  actionLeft,
  actionNew,
  actionRight,
  attributes = {},
  classes = "",
  ctaMain1Variant = "Auto Width",
  subText = "",
  subVisibility = true,
  theme = "Inherit",
  titleText = "",
  titleVariant = "H3",
  visibility = true,
  visualImage = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a69cb8ca361f85b63b37ec5_placeholder.svg",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block
          className={"cta-block_wrap"}
          tag={"aside"}
          {...{
            [theme !== "Square" ? "class" : ""]:
              theme === "Light"
                ? "u-theme-light"
                : theme === "Grey"
                ? "u-theme-grey"
                : theme === "Brand"
                ? "u-theme-brand"
                : theme === "Accent1"
                ? "u-theme-accent1"
                : theme === "Accent2"
                ? "u-theme-accent2"
                : "",
            [classes !== "" ? "class" : ""]: classes,
          }}
          {...attributes}
        >
          <CtaMain
            action={actionNew}
            layoutVariant={"Stack"}
            subText={subText}
            subVariant={"Text Main"}
            subVisibility={subVisibility}
            titleMaxWidth={-1}
            titleText={titleText}
            titleVariant={titleVariant}
            variant={ctaMain1Variant}
          />
          {visualImage.trim() !== "" ? (
            <Block className={"cta-block_visual"} tag={"div"}>
              <Image
                alt={""}
                className={"cta-block_image"}
                height={"auto"}
                loading={"lazy"}
                src={visualImage}
                width={"auto"}
              />
            </Block>
          ) : null}
          <Layout
            column1={
              <CtaMain
                action={actionLeft}
                layoutVariant={"Stack"}
                subText={subText}
                subVariant={"Text Main"}
                subVisibility={subVisibility}
                titleMaxWidth={-1}
                titleText={titleText}
                titleVariant={titleVariant}
              />
            }
            column2={actionRight}
            settingsClasses={"u-gap-8 u-gap-row-5"}
            settingsColumn2Classes={"u-align-self-stretch"}
            settingsVisibility={false}
            variant={"Auto Width"}
          />
          <ThemeSwitcher theme={theme} />
        </Block>
      ) : null}
    </div>
  );
}
