/**
 * @generated
 * @file CtaMain (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { ContentWrapper } from "../wrapper/ContentWrapper";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";

/**
 * CtaMain
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CtaMain({
  action,
  layoutVariant = "Auto Width",
  subMaxWidth = 40,
  subText = "",
  subVariant = "Text Small",
  subVisibility = true,
  titleMaxWidth = 20,
  titleText = "",
  titleVariant = "Inherit",
  variant = "Auto Width",
}) {
  const _styleVariantMap = {
    "Auto Width": "",
    Columns: "w-variant-f15d3589-2d83-5766-c48b-8d4edfde7101",
    Stacked: "w-variant-17313772-ec23-d309-c077-ffc3ca5b2f30",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`cta-block_main ${_activeStyleVariant}`} tag={"div"}>
        <Block
          className={`cta-block_column ${_activeStyleVariant}`}
          tag={"div"}
        >
          <ContentWrapper
            content={
              <>
                <TypographyHeading
                  maxWidth={titleMaxWidth}
                  text={titleText}
                  variant={titleVariant}
                />
                <TypographyParagraph
                  colour={false}
                  maxWidth={subMaxWidth}
                  settingsVisibility={subVisibility}
                  text={subText}
                  variant={subVariant}
                />
              </>
            }
            settingsClasses={"u-margin-trim"}
          />
        </Block>
        {!slotIsEmpty(action) ? (
          <Block
            className={`cta-block_action ${_activeStyleVariant}`}
            tag={"div"}
          >
            <ButtonWrapper content={action} marginTop={0} />
          </Block>
        ) : null}
      </Block>
    </div>
  );
}
