/**
 * @generated
 * @file IconCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { CardPrimary } from "./CardPrimary";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";

/**
 * IconCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function IconCard({
  background = true,
  border = false,

  buttonLink = {
    href: "#",
    preload: "prefetch",
  },

  buttonText = "Button Text",
  buttonVariant = "Link",
  buttonVisibility = false,
  headingText = "",
  headingVariant = "Text Main",
  headingVisibility = true,
  iconClass = "ph-x",
  iconVariant = "Large",
  iconVisibility = true,
  paragraphText = "",
  paragraphVariant = "Text Small",
  paragraphVisibility = true,
  theme = "Inherit",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"cards-wrap_item"} tag={"div"}>
        <CardPrimary
          background={background}
          border={border}
          cardType={"Stacked"}
          content={
            <>
              {iconVisibility ? (
                <Block className={"u-margin-bottom-4"} tag={"div"}>
                  <PhosphorIcon classProp={iconClass} variant={iconVariant} />
                </Block>
              ) : null}
              <TypographyHeading
                maxWidth={-1}
                settingsClasses={"u-text-wrap-balance"}
                settingsVisibility={headingVisibility}
                text={headingText}
                variant={headingVariant}
              />
              <TypographyParagraph
                marginBottom={0}
                settingsClasses={"u-faded"}
                settingsVisibility={paragraphVisibility}
                text={paragraphText}
                variant={paragraphVariant}
              />
              <ButtonWrapper
                content={
                  <ButtonMain
                    icon={<PhosphorIcon classProp={"ph-arrow-right"} />}
                    link={buttonLink}
                    settingsVisibility={true}
                    text={buttonText}
                    variant={buttonVariant}
                  />
                }
                settingsVisibility={buttonVisibility}
              />
            </>
          }
          settingsTheme={theme}
          settingsVisibility={visibility}
        />
      </Block>
    </div>
  );
}
