/**
 * @generated
 * @file ProgressCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { CardPrimary } from "./CardPrimary";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";

/**
 * ProgressCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function ProgressCard({ content, variant = "Base", visual }) {
  const _styleVariantMap = {
    Base: "",
    Vertical: "w-variant-401112b6-d78d-9557-da71-78ddd4f49c8c",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`cards-wrap_item ${_activeStyleVariant}`} tag={"div"}>
        <DOM
          className={`progress-tabs_item ${_activeStyleVariant}`}
          data-progress-tab={"item"}
          style={{
            "--progress": " 1",
            "--opacity": " 1",
          }}
          tag={"div"}
        >
          <CardPrimary
            cardType={
              variant === "Default"
                ? "Default"
                : variant === "Vertical"
                ? "Horizontal"
                : "Default"
            }
            content={content}
            settingsTheme={"Light"}
            visual={visual}
            visualVisibility={!slotIsEmpty(visual) ? true : false}
          />
          <Block className={`progress_wrap ${_activeStyleVariant}`} tag={"div"}>
            <Block
              className={`progress_line ${_activeStyleVariant}`}
              tag={"div"}
            />
          </Block>
        </DOM>
      </Block>
    </div>
  );
}
