/**
 * @generated
 * @file StackedCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { CardPrimary } from "./CardPrimary";
import { IFrame } from "../visual/IFrame";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";
import { VisualImage } from "../visual/VisualImage";
import { slotIsEmpty } from "../webflow_modules/Slots/helpers/slotIsEmpty";

/**
 * StackedCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function StackedCard({
  button,
  cardType = "Stacked",
  headingText = "",
  headingVariant = "Text Main",
  headingVisibility = true,
  paragraphText = "",
  paragraphVariant = "Text Small",
  paragraphVisibility = true,
  v0EmbedSourceUrl = "",
  v0EmbedTitleAccessibility = "UI animation",
  variant = "Base",
  visibility = true,
  visualImageImage = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a69cb8ca361f85b63b37ec5_placeholder.svg",
  visualImageVariant = "Wide 16 / 9",
  visualImageVisibility = true,
}) {
  const _styleVariantMap = {
    Base: "",
    "Fixed Visual": "w-variant-7d21672d-ad43-1a48-961a-2997a854338a",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={`cards-wrap_item ${_activeStyleVariant}`} tag={"div"}>
          <CardPrimary
            cardType={cardType}
            content={
              <>
                <TypographyHeading
                  maxWidth={30}
                  settingsClasses={"u-text-wrap-balance"}
                  settingsVisibility={headingVisibility}
                  text={headingText}
                  variant={headingVariant}
                />
                <TypographyParagraph
                  marginBottom={0}
                  maxWidth={-1}
                  settingsClasses={"u-faded u-text-wrap-pretty"}
                  settingsVisibility={paragraphVisibility}
                  text={paragraphText}
                  variant={paragraphVariant}
                />
                <ButtonWrapper
                  content={button}
                  marginTop={5}
                  settingsVisibility={!slotIsEmpty(button) ? true : false}
                />
              </>
            }
            visual={
              <>
                <VisualImage
                  image={visualImageImage}
                  imageFit={variant === "Fixed Visual" ? false : true}
                  settingsVisibility={
                    !visualImageVisibility || v0EmbedSourceUrl !== ""
                      ? false
                      : true
                  }
                  variant={
                    variant === "Wide 2 / 1" ? visualImageVariant : "Cover"
                  }
                />
                <IFrame
                  title={v0EmbedTitleAccessibility}
                  url={v0EmbedSourceUrl}
                  variant={"v0"}
                  visibility={v0EmbedSourceUrl !== ""}
                />
              </>
            }
          />
        </Block>
      ) : null}
    </div>
  );
}
