/**
 * @generated
 * @file StatCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ButtonMain } from "../button/ButtonMain";
import { ButtonWrapper } from "../wrapper/ButtonWrapper";
import { CardPrimary } from "./CardPrimary";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { PlainHeading } from "../typography/PlainHeading";
import { TypographyHeading } from "../typography/TypographyHeading";
import { TypographyParagraph } from "../typography/TypographyParagraph";
import { TypographyPlain } from "../typography/TypographyPlain";

/**
 * StatCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function StatCard({
  buttonLink = {
    href: "#",
    preload: "prefetch",
  },

  buttonText = "Button Text",
  buttonVariant = "Link",
  buttonVisibility = false,
  plainStat = "Stat",
  plainValue = "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  richStat = "",
  richValue = "",
  theme = "Inherit",
  variant = "Rich",
  visibility = true,
}) {
  const _styleVariantMap = {
    Rich: "",
    Plain: "w-variant-b711639b-7866-5a53-7298-1a9929c8b475",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`cards-wrap_item ${_activeStyleVariant}`} tag={"div"}>
        <CardPrimary
          cardType={"Stacked"}
          content={
            <>
              <PlainHeading
                classes={"u-font-serif"}
                tag={"h4"}
                title={plainStat}
                variant={"H1"}
                visibility={variant === "Plain" ? true : false}
              />
              <TypographyPlain
                settingsAttributes={{
                  class: "u-faded",
                }}
                settingsVisibility={variant === "Plain" ? true : false}
                text={plainValue}
                variant={"Text Small"}
              />
              <TypographyHeading
                maxWidth={30}
                settingsClasses={"u-text-wrap-balance"}
                settingsVisibility={variant === "Square" ? true : false}
                text={richStat}
                variant={"H1"}
              />
              <TypographyParagraph
                marginBottom={0}
                settingsClasses={"u-faded"}
                settingsVisibility={variant === "Square" ? true : false}
                text={richValue}
                variant={"Text Small"}
              />
              <ButtonWrapper
                content={
                  <ButtonMain
                    icon={<PhosphorIcon classProp={"ph-arrow-right"} />}
                    link={buttonLink}
                    settingsVisibility={true}
                    text={buttonText}
                    variant={buttonVariant}
                  />
                }
                settingsVisibility={buttonVisibility}
              />
            </>
          }
          settingsTheme={theme}
          settingsVisibility={visibility}
        />
      </Block>
    </div>
  );
}
