/**
 * @generated
 * @file Collage (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Image from "../webflow_modules/Basic/components/Image";

/**
 * Collage
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Collage({
  image1 = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a8d6ec730a9d633583ccc10_about-tabs-event-group.jpg",
  image2 = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a8d6ec8179cdad202f1470e_about-tabs-team-member.jpg",
  image3 = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a8d6ec82dd5dc6f507f5e88_about-tabs-team-parasol.jpg",
  image4 = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a8d6ec8507db0dcbabd4d16_about-tabs-guests-talking.jpg",
  image5 = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a8d6ec730a9d633583ccc10_about-tabs-event-group.jpg",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"collage_wrap"} tag={"div"}>
        <Block className={"collage_inner"} tag={"div"}>
          <Block className={"collage_asset_wrap is-1"} tag={"div"}>
            <Image
              alt={"Adfin team and customers at a summer event"}
              className={"collage_asset"}
              height={"auto"}
              loading={"lazy"}
              src={image1}
              width={"auto"}
            />
          </Block>
          <Block className={"collage_asset_wrap is-2"} tag={"div"}>
            <Image
              alt={"An Adfin team member in branded kit"}
              className={"collage_asset"}
              height={"auto"}
              loading={"lazy"}
              src={image2}
              width={"auto"}
            />
          </Block>
          <Block className={"collage_asset_wrap is-3"} tag={"div"}>
            <Image
              alt={"Guests under a parasol at an Adfin event"}
              className={"collage_asset"}
              height={"auto"}
              loading={"lazy"}
              src={image3}
              width={"auto"}
            />
          </Block>
          <Block className={"collage_asset_wrap is-4"} tag={"div"}>
            <Image
              alt={"Customers talking at an Adfin event"}
              className={"collage_asset"}
              height={"auto"}
              loading={"lazy"}
              src={image4}
              width={"auto"}
            />
          </Block>
          <Block className={"collage_asset_wrap is-5"} tag={"div"}>
            <Image
              alt={"Adfin team and customers at a summer event"}
              className={"collage_asset"}
              height={"auto"}
              loading={"lazy"}
              src={image5}
              width={"auto"}
            />
          </Block>
        </Block>
      </Block>
    </div>
  );
}
