/**
 * @generated
 * @file IFrame (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * IFrame
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function IFrame({
  classes = "",
  style = "",
  title = "YouTube video player",
  url = "https://www.youtube.com/embed/GPRcAZLuT3U",
  variant = "Base",
  visibility = true,
}) {
  const _styleVariantMap = {
    Base: "",
    Screen: "w-variant-ddeb42a4-4ace-4e9b-9130-343326fd72e7",
    v0: "w-variant-f00450e8-a768-4c50-af47-5c2167f23cb9",
    Cover: "w-variant-5a402a31-64ad-2753-7c2f-826fb62712e3",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <DOM
          className={`u-iframe-wrapper ${classes} ${_activeStyleVariant}`}
          // @ts-ignore - User-defined custom attribute(s)
          style={style}
          tag={"div"}
        >
          <HtmlEmbed
            className={`u-embed-css ${_activeStyleVariant}`}
            content={
              "<style>\nhtml.site-scrollbar .c-iframe {\n\tpointer-events: none;\n}\n</style>"
            }
          />
          <DOM
            // @ts-ignore - User-defined custom attribute(s)
            allow={
              "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            }
            allowFullScreen={true}
            className={`u-iframe ${_activeStyleVariant}`}
            frameBorder={"0"}
            referrerPolicy={"strict-origin-when-cross-origin"}
            src={url}
            tag={"iframe"}
            title={title}
          />
        </DOM>
      ) : null}
    </div>
  );
}
