/**
 * @generated
 * @file MediaOverlay (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * MediaOverlay
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function MediaOverlay({
  settingsClasses = " ",
  settingsOverlayStrength = 70,
  settingsVisibility = true,
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Gradient: "w-variant-9653c0cc-21fc-fb82-1373-c98b1644e5a8",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <DOM
          className={`u-overlay ${settingsClasses} ${_activeStyleVariant}`}
          data-number={formatNumber(-1)(settingsOverlayStrength)}
          tag={"div"}
        />
      ) : null}
    </div>
  );
}
