/**
 * @generated
 * @file VideoWrap (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ThemeSwitcher } from "../variantSwitcher/ThemeSwitcher";
import { VisualVideo } from "./VisualVideo";

/**
 * VideoWrap
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function VideoWrap({
  theme = "Inherit",
  visualVideoSettingsAttributes = {},
  visualVideoSettingsAutoplay = false,
  visualVideoSettingsLoop = false,
  visualVideoSettingsMuted = true,
  visualVideoUrl = "https://content.adfin.com/ABC-06-how-to-refer.mp4",
  visualVideoVariant = "Square 1 / 1",
  visualVideoVideoFit = false,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"video_wrap"}
        tag={"div"}
        {...{
          [theme !== "Square" ? "class" : ""]:
            theme === "Light"
              ? "u-theme-light"
              : theme === "Grey"
              ? "u-theme-grey"
              : theme === "Brand"
              ? "u-theme-brand"
              : theme === "Accent1"
              ? "u-theme-accent1"
              : theme === "Accent2"
              ? "u-theme-accent2"
              : theme === "Dark"
              ? "u-theme-dark"
              : "",
        }}
      >
        <VisualVideo
          settingsAutoplay={visualVideoSettingsAutoplay}
          settingsLoop={visualVideoSettingsLoop}
          settingsMuted={visualVideoSettingsMuted}
          url={visualVideoUrl}
          variant={visualVideoVariant}
          videoFit={visualVideoVideoFit}
        />
        <ThemeSwitcher theme={theme} />
      </Block>
    </div>
  );
}
