/**
 * @generated
 * @file VisualImage (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Image from "../webflow_modules/Basic/components/Image";

/**
 * VisualImage
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function VisualImage({
  corners = false,
  fetchPriority = false,
  image = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a69cb8ca361f85b63b37ec5_placeholder.svg",
  imageFit = false,
  loading = false,
  settingsAltText = "__wf_reserved_inherit",
  settingsAttributes = {},
  settingsVisibility = false,
  variant = "Wide 16 / 9",
}) {
  const _styleVariantMap = {
    "Wide 2 / 1": "",
    "Wide 16 / 9": "w-variant-27d05669-180c-3169-9b64-0eda31f8d4d3",
    "Wide 3 / 2": "w-variant-57c7d8f5-d942-5de8-0712-e12fff699502",
    "Wide 5 / 4": "w-variant-8e41429f-9f9e-7697-357e-815bd3e59383",
    "Square 1 / 1": "w-variant-a5f35569-5171-ee3d-f7bb-c5b2372249ac",
    "Tall 4 / 5": "w-variant-35ea7d22-774e-1ba9-1dcc-8a392636f83d",
    "Tall 2 / 3": "w-variant-a93327ec-aace-62d3-860b-21ee12acd25a",
    Auto: "w-variant-dc088902-c60f-c2fd-b569-4aae6786457a",
    Cover: "w-variant-4972adff-107c-1f37-d19c-526a2bf55c28",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility ? (
        <Block
          className={`u-image-wrapper ${_activeStyleVariant}`}
          tag={"div"}
          {...{
            [!imageFit ? "class" : ""]: !imageFit
              ? "u-background-transparent u-object-fit-contain"
              : "",
            [!corners ? "class" : ""]: !corners ? "u-radius-main" : "",
          }}
          {...settingsAttributes}
        >
          {image.trim() !== "" ? (
            <Image
              className={`u-image ${_activeStyleVariant}`}
              // @ts-ignore - User-defined custom attribute(s)
              draggable={"false"}
              height={"auto"}
              src={image}
              width={"auto"}
              {...{
                [!fetchPriority ? "fetchpriority" : ""]: !fetchPriority
                  ? "high"
                  : "",
              }}
            />
          ) : null}
        </Block>
      ) : null}
    </div>
  );
}
