/**
 * @generated
 * @file VisualVideo (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * VisualVideo
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function VisualVideo({
  corners = false,
  settingsAttributes = {},
  settingsAutoplay = false,
  settingsControls = false,
  settingsLoop = false,
  settingsMuted = false,
  settingsStyle = "",
  settingsVisibility = false,
  url = "https://timothyricks.us.getafile.online/background-video",
  variant = "Wide 16 / 9",
  videoFit = false,
}) {
  const _styleVariantMap = {
    "Wide 2 / 1": "",
    "Wide 16 / 9": "w-variant-0b00a75a-35ba-66c2-fce0-21c117d62ce0",
    "Wide 3 / 2": "w-variant-a9490bed-5b56-7b46-8413-993d16d77e88",
    "Wide 5 / 4": "w-variant-8157ca33-45d5-df1a-bd25-894298c8e117",
    "Square 1 / 1": "w-variant-ec7f8a9f-99ac-b5a5-140b-730400a62670",
    "Tall 4 / 5": "w-variant-f3f45657-6a73-93f9-25db-a80af56ad72a",
    "Tall 2 / 3": "w-variant-c3ccbb6c-6fa7-1113-0f2e-08b77dffca68",
    "Portrait 9 / 16": "w-variant-4fdcad4d-3108-23d5-24a2-112c4afc6803",
    Cover: "w-variant-db26956a-7929-76af-05b0-02971cbab2f4",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && url !== "" ? (
        <DOM className={`u-video ${_activeStyleVariant}`} tag={"video"} />
      ) : null}
    </div>
  );
}
