import { anchorId } from './anchorId';
import { anchorLinks } from './anchorLinks';
import { anchorScroll } from './anchorScroll';
import { askAi } from './askAi';
import { changelogVideo } from './changelogVideo';
import { customerLogos } from './customerLogos';
import { duoTab } from './duoTab';
import { emailHandoff } from './emailHandoff';
import { eventMap } from './eventMap';
import { faqSchema } from './faqSchema';
import { faqSearch } from './faqSearch';
import { hubMap } from './hubMap';
import { hubspotForms } from './hubspotForms';
import { progressTab } from './progressTab';
import { rotatingTitle } from './rotatingTitle';
import { toc } from './toc';
import { tracking } from './tracking';
import { transition } from './transition';
import { uiScreenshot } from './uiScreenshot';
import { utmForward } from './utmForward';
import { videoControls } from './videoControls';
import { wheel } from './wheel';

export const components = (): void => {
  anchorId();
  anchorLinks();
  anchorScroll();
  askAi();
  changelogVideo();
  customerLogos();
  duoTab();
  emailHandoff();
  eventMap();
  faqSchema();
  faqSearch();
  hubMap();
  hubspotForms();
  progressTab();
  rotatingTitle();
  toc();
  tracking();
  transition();
  uiScreenshot();
  utmForward();
  videoControls();
  wheel();
};
