/**
 * @generated
 * @file BlogCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { Author } from "../post/Author";
import { Clickable } from "../utility/Clickable";
import { PlainHeading } from "../typography/PlainHeading";
import { TypographyPlain } from "../typography/TypographyPlain";
import { VisualImage } from "../visual/VisualImage";

/**
 * BlogCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function BlogCard({
  authorAvatar = "",
  authorName = "Author Name",
  authorPublishDate = "MMMM D, YYYY",
  authorReadTime = "N",
  authorRole = "Author Role",
  cardSnippet = "Lorem ipsum dolor sit amet, consectetur adipiscing elit",

  clickableLink = {
    href: "#",
  },

  clickableScreenReaderText = "",
  name = "Heading",
  slug = "",
  thumbnail = "",
  topic = "Topic",
  visualImageSettingsAltText = "__wf_reserved_inherit",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"blog_card_wrap"}
        data-card-slug={slug}
        data-trigger={"hover focus"}
        tag={"div"}
      >
        <Clickable
          link={clickableLink}
          screenReaderText={clickableScreenReaderText}
        />
        <Block className={"blog_card_background is-top"} tag={"div"} />
        <Block className={"blog_card_background"} tag={"div"} />
        <Block className={"blog_card_thumbnail"} tag={"div"}>
          <VisualImage
            image={thumbnail}
            settingsAltText={visualImageSettingsAltText}
            variant={"Square 1 / 1"}
          />
        </Block>
        <Block className={"blog_card_content"} tag={"div"}>
          <Block className={"resource-tag_component is-card"} tag={"div"}>
            <Block
              className={"resource-tag_text u-text-style-xsmall"}
              tag={"div"}
            >
              {topic}
            </Block>
          </Block>
          <PlainHeading maxWidth={-1} tag={"h5"} title={name} />
          <TypographyPlain
            marginBottom={0}
            settingsAttributes={{
              class: "u-line-clamp-2",
            }}
            text={cardSnippet}
          />
          <Block className={"blog_card_sub"} tag={"div"}>
            <Author
              avatar={authorAvatar}
              name={authorName}
              resourceMetaPublishDate={authorPublishDate}
              resourceMetaReadTime={authorReadTime}
              resourceMetaShowMeta={true}
              role={authorRole}
            />
          </Block>
        </Block>
      </Block>
    </div>
  );
}
