/**
 * @generated
 * @file BlogCards (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";
import { BlogCard } from "./BlogCard";

/**
 * BlogCards
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported elements: `Collection List Items`, `Empty State`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function BlogCards({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NotSupported _atom={"Collection List"}>
        <NotSupported _atom={"Collection List Items"} />
        <NotSupported _atom={"Empty State"} />
      </NotSupported>
    </div>
  );
}
