/**
 * @generated
 * @file CaseStudyCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Image from "../webflow_modules/Basic/components/Image";
import { ButtonAction } from "../button/ButtonAction";
import { Clickable } from "../utility/Clickable";
import { VisualImage } from "../visual/VisualImage";

/**
 * CaseStudyCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CaseStudyCard({
  backgroundAlt = "__wf_reserved_inherit",
  backgroundImage = "https://cdn.prod.website-files.com/6a69cb89a361f85b63b37d60/6a69cb8ca361f85b63b37ec5_placeholder.svg",

  link = {
    href: "#",
  },

  logo = "",
  name = "",
  quote = "Tempor deserunt officia consequat velit voluptate laboris sunt ex labore. Culpa elit non Lorem nisi.",
  showQuoteMarks = false,
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Square: "w-variant-cb88a656-1039-836a-a2c3-a78e4c1f7c9e",
    Auto: "w-variant-ba78c9ad-2547-af92-c375-7c781840039c",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`case-study-snippets_card ${_activeStyleVariant}`}
        data-trigger={"hover focus"}
        tag={"div"}
      >
        <Clickable link={link} screenReaderText={name} />
        <Block
          className={`case-study-snippets_item_inner ${_activeStyleVariant}`}
          tag={"div"}
        >
          <VisualImage
            image={backgroundImage}
            imageFit={true}
            settingsAltText={backgroundAlt}
            variant={"Cover"}
          />
          {logo.trim() !== "" ? (
            <Image
              alt={""}
              className={`case-study-snippets_item_logo ${_activeStyleVariant}`}
              height={"auto"}
              loading={"lazy"}
              src={logo}
              width={"auto"}
            />
          ) : null}
          <Block
            className={`case-study-snippets_item_content ${_activeStyleVariant}`}
            tag={"div"}
          >
            <DOM
              className={`u-text-style-large u-line-clamp-3 ${_activeStyleVariant}`}
              tag={"p"}
            >
              {showQuoteMarks ? <DOM tag={"span"}>{"“"}</DOM> : null}
              <DOM tag={"span"}>{quote}</DOM>
            </DOM>
          </Block>
          <Block
            className={`case-study-snippets_item_link ${_activeStyleVariant}`}
            tag={"div"}
          >
            <ButtonAction link={link} phosphorIconClass={"ph-arrow-up-right"} />
          </Block>
        </Block>
      </Block>
    </div>
  );
}
