/**
 * @generated
 * @file CustomerLogos (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Image from "../webflow_modules/Basic/components/Image";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";
import { CardPrimary } from "../card/CardPrimary";
import { CardsList } from "../card/CardsList";
import { PhosphorIcon } from "../typography/PhosphorIcon";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * CustomerLogos
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported props: `Filters`, `Sort`
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CustomerLogos({
  limit = 100,
  minWidth = 10,
  variant = "Base",
}) {
  const _styleVariantMap = {
    Base: "",
    Square: "w-variant-ed11dfc3-a721-2dca-a574-a1fb67340dc2",
    Marquee: "w-variant-a5a88377-d50c-d46d-9b54-0e21dc8e3fce",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`u-display-contents ${_activeStyleVariant}`}
        data-component={"customer-logos"}
        data-customer-logos-show={formatNumber(-1)(limit)}
        tag={"div"}
      >
        <CardsList
          card={<NotSupported _atom={"Collection List"} />}
          settingsMinWidth={minWidth}
          theme={"Inherit"}
        />
      </Block>
    </div>
  );
}
