/**
 * @generated
 * @file CustomerStories (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";
import { CaseStudyCard } from "./CaseStudyCard";
import { VisualImage } from "../visual/VisualImage";

/**
 * CustomerStories
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported props: `Filters`, `Sort`
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function CustomerStories({
  minWidth = 18,
  show = 100,
  variant = "Square",
}) {
  const _styleVariantMap = {
    Square: "",
    "Equal Height": "w-variant-02465303-acc3-44de-0448-6dd18c2576f1",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`u-display-contents ${_activeStyleVariant}`}
        tag={"div"}
      >
        <HtmlEmbed className={`u-embed-css ${_activeStyleVariant}`} />
        <NotSupported _atom={"Collection List"} />
      </Block>
    </div>
  );
}
