/**
 * @generated
 * @file Customers (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { CustomerLogos } from "./CustomerLogos";
import { CustomerStories } from "./CustomerStories";
import { formatNumber } from "../webflow_modules/Builtin/helpers/formatNumber";

/**
 * Customers
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported props: `Customer Logos/Filters`, `Customer Logos/Sort`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Customers({
  customerLogosLimit = 10,
  customerLogosMinWidth = 10,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"customers_component"}
        data-component={"customers"}
        data-customer-logos-show={formatNumber(-1)(customerLogosLimit)}
        tag={"div"}
      >
        <HtmlEmbed className={"u-embed-css"} />
        <Block className={"customers_quote"} tag={"div"}>
          <CustomerStories show={1} />
        </Block>
        <Block className={"customers_logos"} tag={"div"}>
          <CustomerLogos
            filters={customerLogosFilters}
            limit={customerLogosLimit}
            minWidth={customerLogosMinWidth}
            sort={customerLogosSort}
          />
        </Block>
      </Block>
    </div>
  );
}
