/**
 * @generated
 * @file EventCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Image from "../webflow_modules/Basic/components/Image";
import { ButtonMain } from "../button/ButtonMain";
import { Clickable } from "../utility/Clickable";
import { PlainHeading } from "../typography/PlainHeading";
import { Tag } from "../typography/Tag";
import { TypographyPlain } from "../typography/TypographyPlain";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * EventCard
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function EventCard({
  buttonText = "Learn More",
  date = "date",
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  heading = "Heading",
  image = "",

  link = {
    href: "#",
  },

  location = "Online",
  screenReaderText = "Learn More",
  settingsCardAttributes = {},
  settingsClickableAttributes = {},
  settingsRole = true,
  settingsTheme = "Inherit",
  settingsVisibility = false,
  settingsWrapperClasses = "",
  settingsWrapperStyle = "",
  type = "Webinar",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {settingsVisibility && !!toText(heading) ? (
        <DOM
          className={"card_primary_wrap"}
          tag={"div"}
          {...{
            [settingsWrapperClasses !== "" ? "class" : ""]:
              settingsWrapperClasses,
            [settingsWrapperStyle !== "" ? "style" : ""]: settingsWrapperStyle,
            [settingsRole ? "" : "role"]: settingsRole ? "" : "listitem",
          }}
        >
          <Block
            className={"card_primary_group"}
            data-trigger={"hover-if-clickable focus"}
            tag={"div"}
          >
            <Block
              className={"card_primary_element"}
              tag={"div"}
              {...settingsCardAttributes}
            >
              <Block className={"card_primary_content"} tag={"div"}>
                <Block className={"card_primary_header"} tag={"div"}>
                  <Block className={"card_primary_meta"} tag={"div"}>
                    <Tag
                      marginBottom={0}
                      phosphorIconVisibility={false}
                      text={type}
                      theme={"Accent1"}
                    />
                    <Block className={"card_primary_info"} tag={"div"}>
                      <Block className={"u-text-style-eyebrow"} tag={"div"}>
                        {date}
                      </Block>
                      <Block className={"u-dot"} tag={"div"} />
                      <Block className={"u-text-style-eyebrow"} tag={"div"}>
                        {location}
                      </Block>
                    </Block>
                  </Block>
                  <Block tag={"div"}>
                    <PlainHeading
                      maxWidth={-1}
                      tag={"h3"}
                      title={heading}
                      variant={"H5"}
                    />
                    <TypographyPlain
                      settingsAttributes={{
                        class: "u-faded",
                      }}
                      text={description}
                      variant={"Text Small"}
                    />
                  </Block>
                </Block>
                <ButtonMain
                  settingsClickableVisibility={false}
                  settingsVisibility={!!toText(buttonText) ? true : false}
                  text={buttonText}
                  variant={"Primary"}
                />
              </Block>
              <Block className={"card_primary_visual"} tag={"div"}>
                <Image
                  alt={""}
                  className={"card_primary_image"}
                  height={"auto"}
                  loading={"lazy"}
                  src={image}
                  width={"auto"}
                />
              </Block>
            </Block>
            <Clickable
              link={link}
              screenReaderText={screenReaderText}
              visibility={!!toText(screenReaderText) ? true : false}
            />
          </Block>
        </DOM>
      ) : null}
    </div>
  );
}
