/**
 * @generated
 * @file IntegrationsWheel (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Image from "../webflow_modules/Basic/components/Image";
import NotSupported from "../webflow_modules/Builtin/components/NotSupported";

/**
 * IntegrationsWheel
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function IntegrationsWheel({}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"integrations-wheel_component"}
        data-component={"wheel"}
        data-wheel-timeline={"css"}
        tag={"div"}
      >
        <HtmlEmbed
          className={"u-embed-css"}
          content={
            "<style>\n  .integrations-wheel_overlay::after {\n    content: '';\n    position: absolute;\n    z-index: 2;\n    inset: auto 0 0;\n    height: 8rem;\n\n    pointer-events: none;\n\n    backdrop-filter: blur(0.25rem);\n    -webkit-backdrop-filter: blur(0.25rem);\n\n    mask-image: linear-gradient(to bottom, transparent 0%, black 100%);\n    -webkit-mask-image: linear-gradient(to bottom, transparent 0%, black 100%);\n  }\n\n  .integrations-wheel_component {\n    --wheel-sweep: 180deg; /* top half only */\n    animation: wheel-scroll linear both;\n    animation-timeline: view(); /* progress as the section scrolls in */\n  }\n  @keyframes wheel-scroll {\n    from {\n      --wheel-progress: 0;\n    }\n    to {\n      --wheel-progress: 1;\n    }\n  }\n</style>"
          }
        />
        <Block className={"integrations-wheel_box"} tag={"div"}>
          <Block
            className={"integrations-wheel_circle"}
            data-wheel={"circle"}
            tag={"div"}
          />
          <Block
            className={"integrations-wheel_circle is-second"}
            data-wheel={"circle"}
            tag={"div"}
          />
          <Block
            className={"integrations-wheel_circle is-third"}
            data-wheel={"circle"}
            tag={"div"}
          />
          <NotSupported _atom={"Collection List"} />
        </Block>
        <Block className={"integrations-wheel_overlay"} tag={"div"} />
      </Block>
    </div>
  );
}
