/**
 * @generated
 * @file PostContent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import RichText from "../webflow_modules/Basic/components/RichText";
import { Author } from "../post/Author";
import { BorderDivider } from "../decorative/BorderDivider";
import { ShareLinks } from "../post/ShareLinks";
import { TableOfContents } from "./TableOfContents";

/**
 * PostContent
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function PostContent({
  authorAvatar = "",
  authorName = "Author Name",
  authorRole = "Author Role",
  content = "",
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"post_content_component"} id={"section"} tag={"div"}>
        <TableOfContents />
        <Block className={"post_content_body"} tag={"div"}>
          <RichText
            className={"post_content_text u-rich-text"}
            fs-toc-element={"contents"}
            fs-toc-offsettop={"var(--helpers--scroll-margin-top)"}
            tag={"div"}
          >
            {content}
          </RichText>
          <BorderDivider marginBlock={5} />
          <Author avatar={authorAvatar} name={authorName} role={authorRole} />
          <BorderDivider marginBlock={5} />
          <ShareLinks variant={"Vertical"} />
        </Block>
      </Block>
    </div>
  );
}
