/**
 * @generated
 * @file TableOfContents (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { TocLink } from "../miscellaneous/TocLink";

/**
 * TableOfContents
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function TableOfContents({ tocLink, variant = "Base" }) {
  const _styleVariantMap = {
    Base: "",
    Manual: "w-variant-5c8e7b08-d372-182e-f747-9b4c05a03dc7",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM
        aria-label={"Table of contents"}
        className={`toc_wrap ${_activeStyleVariant}`}
        role={"list"}
        tag={"div"}
      >
        <DOM
          aria-label={"Table of contents"}
          className={`toc_component ${_activeStyleVariant}`}
          tag={"div"}
        >
          {variant === "Square" ? (
            <Block
              className={`toc_links ${_activeStyleVariant}`}
              data-toc={"links"}
              // @ts-ignore - User-defined custom attribute(s)
              role={"list"}
              tag={"div"}
            >
              <TocLink />
            </Block>
          ) : null}
          {tocLink}
          <Block
            className={`toc_border_wrap ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`toc_border is-above ${_activeStyleVariant}`}
              tag={"div"}
            />
            <Block
              className={`toc_border ${_activeStyleVariant}`}
              tag={"div"}
            />
          </Block>
        </DOM>
      </DOM>
    </div>
  );
}
