/**
 * @generated
 * @file Author (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import { ResourceMeta } from "../miscellaneous/ResourceMeta";
import { VisualImage } from "../visual/VisualImage";
import { toText } from "../webflow_modules/ListOfElements/helpers/toText";

/**
 * Author
 *
 * @see {@link https://ss-adfin-staging.design.webflow.com | Source site in Webflow}
 */
export function Author({
  avatar = "",
  classes = "",
  name = "Author Name",
  resourceMetaPublishDate = "MMMM D, YYYY",
  resourceMetaReadTime = "N",
  resourceMetaShowMeta = false,
  role = "Author Role",
  visibility = true,
}) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {visibility ? (
        <Block className={`author_component u-gap-3 ${classes}`} tag={"div"}>
          <Block className={"author_thumbnail"} tag={"div"}>
            <VisualImage image={avatar} variant={"Square 1 / 1"} />
          </Block>
          <Block className={"author_info u-gap-1"} tag={"div"}>
            {!!toText(name) ? (
              <Block className={"u-text-style-small"} tag={"div"}>
                {name}
              </Block>
            ) : null}
            {!!toText(role) && !resourceMetaShowMeta ? (
              <Block className={"u-text-style-xsmall u-faded"} tag={"div"}>
                {role}
              </Block>
            ) : null}
            <ResourceMeta
              publishDate={resourceMetaPublishDate}
              readTime={resourceMetaReadTime}
              visibility={resourceMetaShowMeta}
            />
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
